/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.ra.View.task;

import com.ra.Controller.DepartmentController;
import com.ra.Controller.ProjectController;
import com.ra.Controller.TaskController;
import com.ra.Model.Entity.Department;
import com.ra.Model.Entity.Project;
import com.ra.Model.Entity.Tasks;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author HP
 */
public class AddTask extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddTask.class.getName());
    private final TaskController taskController = new TaskController();
    private final DepartmentController departmentController = new DepartmentController();
    private final ProjectController projectController = new ProjectController();
    // Danh sách dữ liệu nạp vào combobox
    private List<Department> departmentList = new ArrayList<>();
    private List<Project> projectList = new ArrayList<>();


    /**
     * Creates new form CreateNewTask
     */
    public AddTask(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        loadDepartments();
        loadProjects();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTaskname = new javax.swing.JTextField();
        lbTaskname = new javax.swing.JLabel();
        lbDepartmentname = new javax.swing.JLabel();
        cbDepartmentname = new javax.swing.JComboBox<>();
        cbProjectname = new javax.swing.JComboBox<>();
        lbProjectname = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbTaskname.setText("タスク名");

        lbDepartmentname.setText("部署名");

        lbProjectname.setText("プロジェクト名");

        btnCancel.setBackground(new java.awt.Color(255, 153, 0));
        btnCancel.setText("キャンセル");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setBackground(new java.awt.Color(102, 255, 102));
        btnSave.setText("保存");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbTaskname)
                            .addComponent(lbDepartmentname))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTaskname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDepartmentname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTaskname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaskname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDepartmentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDepartmentname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProjectname))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
                                         

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {

        String taskName = txtTaskname.getText().trim();
        if (taskName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Task name cannot be empty!");
            return;
        }

        int depIndex = cbDepartmentname.getSelectedIndex();
        int projIndex = cbProjectname.getSelectedIndex();

        // Lấy Department
        Department selectedDept = null;
        if (depIndex >= 0 && departmentList != null && depIndex < departmentList.size()) {
            selectedDept = departmentList.get(depIndex);
        }

        // Lấy Project
        Project selectedProject = null;
        if (projIndex >= 0 && projectList != null && projIndex < projectList.size()) {
            selectedProject = projectList.get(projIndex);
        }

        // Tạo list an toàn — KHÔNG BAO GIỜ LỖI
        List<Department> deps = new java.util.ArrayList<>();
        if (selectedDept != null) deps.add(selectedDept);

        List<Project> projs = new java.util.ArrayList<>();
        if (selectedProject != null) projs.add(selectedProject);

        // Tạo Task
        Tasks task = new Tasks();
        task.setName(taskName);
        task.setDepartments(deps);
        task.setProjects(projs);

        // Save
        taskController.create(task);

        JOptionPane.showMessageDialog(this, "Task created successfully!");
        this.dispose();
    }

                                       

    private void loadDepartments() {
        departmentList = departmentController.findAll();
        cbDepartmentname.removeAllItems();

        for (Department d : departmentList) {
            cbDepartmentname.addItem(d.getName());
        }
    }

    private void loadProjects() {
        projectList = projectController.findAll();
        cbProjectname.removeAllItems();

        for (Project p : projectList) {
            cbProjectname.addItem(p.getName());
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddTask dialog = new AddTask(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbDepartmentname;
    private javax.swing.JComboBox<String> cbProjectname;
    private javax.swing.JLabel lbDepartmentname;
    private javax.swing.JLabel lbProjectname;
    private javax.swing.JLabel lbTaskname;
    private javax.swing.JTextField txtTaskname;
    // End of variables declaration//GEN-END:variables
}
