package com.ra.View.task;

import com.ra.Controller.DepartmentController;
import com.ra.Controller.ProjectController;
import com.ra.Controller.TaskController;
import com.ra.Model.Entity.Department;
import com.ra.Model.Entity.Project;
import com.ra.Model.Entity.Tasks;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

public class AddTask extends javax.swing.JPanel {

    // 1. CHUYỂN KHAI BÁO CONTROLLER VÀ DANH SÁCH DỮ LIỆU
    private static final java.util.logging.Logger logger = Logger.getLogger(AddTask.class.getName());
    private final TaskController taskController = new TaskController();
    private final DepartmentController departmentController = new DepartmentController();
    private final ProjectController projectController = new ProjectController();

    // Danh sách dữ liệu nạp vào combobox
    private List<Department> departmentList = new ArrayList<>();
    private List<Project> projectList = new ArrayList<>();

    public AddTask() {
        initComponents();

        // 3. GỌI HÀM TẢI DỮ LIỆU VÀ GẮN LẠI SỰ KIỆN
        loadDepartments();
        loadProjects();
        // Gắn lại sự kiện cho các nút
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        btnSave.addActionListener(this::btnSaveActionPerformed);
    }

    // 2. CHUYỂN CÁC PHƯƠNG THỨC TẢI DỮ LIỆU (Load Data)

    private void loadDepartments() {
        departmentList = departmentController.findAll();
        cbDepartmentname.removeAllItems();

        for (Department d : departmentList) {
            cbDepartmentname.addItem(d.getName());
        }
    }

    private void loadProjects() {
        projectList = projectController.findAll();
        cbProjectname.removeAllItems();

        for (Project p : projectList) {
            cbProjectname.addItem(p.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProjectname = new javax.swing.JComboBox<>();
        lbProjectname = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        txtTaskname = new javax.swing.JTextField();
        lbTaskname = new javax.swing.JLabel();
        lbDepartmentname = new javax.swing.JLabel();
        cbDepartmentname = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        lbProjectname.setText("プロジェクト名");

        btnCancel.setBackground(new java.awt.Color(255, 153, 0));
        btnCancel.setText("キャンセル");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setBackground(new java.awt.Color(102, 255, 102));
        btnSave.setText("保存");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lbTaskname.setText("タスク名");

        lbDepartmentname.setText("部署名");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbTaskname)
                                    .addComponent(lbDepartmentname))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTaskname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDepartmentname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTaskname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaskname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDepartmentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDepartmentname))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProjectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProjectname))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // 4. CHUYỂN CÁC PHƯƠNG THỨC XỬ LÝ SỰ KIỆN

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        // Trong JPanel, cần đóng cửa sổ cha (thường là JFrame hoặc JDialog) chứa nó.
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {

        String taskName = txtTaskname.getText().trim();
        if (taskName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Task name cannot be empty!");
            return;
        }

        int depIndex = cbDepartmentname.getSelectedIndex();
        int projIndex = cbProjectname.getSelectedIndex();

        // Lấy đối tượng từ danh sách đã load (dùng index của ComboBox)
        Department selectedDept = depIndex >= 0 ? departmentList.get(depIndex) : null;
        Project selectedProject = projIndex >= 0 ? projectList.get(projIndex) : null;

        List<Department> deps = new ArrayList<>();
        if (selectedDept != null) deps.add(selectedDept);

        List<Project> projs = new ArrayList<>();
        if (selectedProject != null) projs.add(selectedProject);

        // TẠO TASK
        Tasks task = new Tasks();
        task.setName(taskName);
        task.setTaskCode(Tasks.generateTaskCode());
        task.setDepartments(deps);
        task.setProjects(projs);

        // Cập nhật quan hệ ngược lại
        if (selectedDept != null) {
            // Đảm bảo list được khởi tạo
            if (selectedDept.getTasks() == null) selectedDept.setTasks(new ArrayList<>());
            selectedDept.getTasks().add(task);
        }
        if (selectedProject != null) {
            // Đảm bảo list được khởi tạo
            if (selectedProject.getTasks() == null) selectedProject.setTasks(new ArrayList<>());
            selectedProject.getTasks().add(task);
        }

        // SAVE
        taskController.create(task);

        JOptionPane.showMessageDialog(this, "Task created successfully!");

        // Đóng cửa sổ cha sau khi lưu thành công
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbDepartmentname;
    private javax.swing.JComboBox<String> cbProjectname;
    private javax.swing.JLabel lbDepartmentname;
    private javax.swing.JLabel lbProjectname;
    private javax.swing.JLabel lbTaskname;
    private javax.swing.JTextField txtTaskname;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Tạo một JFrame tạm thời để chứa JPanel AddTask1
            JFrame frame = new JFrame("プロジェクトとタスク追加 (テスト)");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            // Thêm JPanel vào JFrame
            frame.add(new AddTask());

            // Tự động điều chỉnh kích thước và hiển thị
            frame.pack();
            frame.setLocationRelativeTo(null); // Đặt ở giữa màn hình
            frame.setVisible(true);
        });
    }
}