package com.ra.View.task;

import com.ra.Controller.TaskController;
import com.ra.Model.Entity.Department;
import com.ra.Model.Entity.Project;
import com.ra.Model.Entity.Tasks;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.logging.Logger;

public class AllTask extends javax.swing.JPanel {

    // 1. KHAI BÁO CONTROLLER VÀ LOGGER
    private final TaskController taskController = new TaskController();
    private static final java.util.logging.Logger logger =
            Logger.getLogger(AllTask.class.getName());

    /**
     * Creates new form AllTask1
     */
    public AllTask() {
        initComponents();
        // Tải dữ liệu ban đầu
        loadTable(taskController.findAll());

        // Gắn lại sự kiện cho các nút Edit và Delete (nếu bạn cần xử lý sự kiện cho chúng)
        btnEdit.addActionListener(this::btnEditActionPerformed);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrAddtask = new javax.swing.JScrollPane();
        tblAddtask = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        btnAddTask = new javax.swing.JButton();
        lbKeywork = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnAll = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEdit.addActionListener(this::btnEditActionPerformed);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);


        setBackground(new java.awt.Color(255, 255, 255));

        tblAddtask.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "タスク名", "プロジェクト名", "部署名"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrAddtask.setViewportView(tblAddtask);

        btnSearch.setText("検索");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnAddTask.setText("タスク作成");
        btnAddTask.addActionListener(this::btnAddTaskActionPerformed);

        lbKeywork.setText("キーワード");

        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnAll.setText("全て");
        btnAll.addActionListener(this::btnAllActionPerformed);

        btnEdit.setText("編集");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setText("削除");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 679, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(scrAddtask, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(78, 78, 78)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbKeywork, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83)
                            .addComponent(btnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(79, 79, 79)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(103, 103, 103)
                    .addComponent(scrAddtask, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddTask)
                        .addComponent(lbKeywork)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSearch)
                        .addComponent(btnAll))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 291, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete))
                    .addGap(68, 68, 68)))
        );
    }// </editor-fold>//GEN-END:initComponents

    // 2. CHUYỂN CÁC PHƯƠNG THỨC XỬ LÝ SỰ KIỆN

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {

        int row = tblAddtask.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "タスクを選択してください！");
            return;
        }

        int id = Integer.parseInt(tblAddtask.getValueAt(row, 0).toString());

        taskController.findById(id).ifPresentOrElse(task -> {
            AddTask dialog = new AddTask(null, true, task);
            dialog.setVisible(true);

            loadTable(taskController.findAll());

        }, () -> JOptionPane.showMessageDialog(this, "Task not found!"));
    }


    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {

        int row = tblAddtask.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "タスクを選択してください！");
            return;
        }

        int id = Integer.parseInt(tblAddtask.getValueAt(row, 0).toString());

        if (JOptionPane.showConfirmDialog(this, "削除しますか？") == JOptionPane.YES_OPTION) {

            if (taskController.delete(id)) {
                JOptionPane.showMessageDialog(this, "削除完了！");
                loadTable(taskController.findAll());
            } else {
                JOptionPane.showMessageDialog(this, "削除失敗！");
            }
        }
    }


    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
        String keyword = txtSearch.getText().trim();

        if (keyword.isEmpty()) {
            loadTable(taskController.findAll());
            return;
        }

        List<Tasks> results = taskController.search(keyword);

        if (results.isEmpty()) {
            JOptionPane.showMessageDialog(this, "検索結果がありません！");
        }

        loadTable(results);
    }


    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {
        AddTask dialog = new AddTask(null, true);
        dialog.setVisible(true);
        loadTable(taskController.findAll()); // reload
    }

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // Xử lý sự kiện Enter trong ô tìm kiếm
        btnSearchActionPerformed(evt);
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        loadTable(taskController.findAll());
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO: Xử lý sự kiện Edit
        int selectedRow = tblAddtask.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "編集するタスクを選択してください。", "注意", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Thêm logic mở dialog EditTask tại đây
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: Xử lý sự kiện Delete
        int selectedRow = tblAddtask.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "削除するタスクを選択してください。", "注意", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Thêm logic xóa task tại đây
    }

    // 3. CHUYỂN PHƯƠNG THỨC TẢI DỮ LIỆU
    private void loadTable(List<Tasks> list) {

        String[] cols = {"ID", "タスク名", "プロジェクト名", "部署名"};
        DefaultTableModel model = new DefaultTableModel(cols, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (Tasks t : list) {

            String projectNames = t.getProjects() == null ? "" :
                    t.getProjects().stream().map(Project::getName)
                            .reduce("", (a, b) -> a + (a.isEmpty() ? "" : ", ") + b);

            String departmentNames = t.getDepartments() == null ? "" :
                    t.getDepartments().stream().map(Department::getName)
                            .reduce("", (a, b) -> a + (a.isEmpty() ? "" : ", ") + b);

            model.addRow(new Object[]{
                    t.getId(),             // ⭐ Cột 0 BẮT BUỘC là ID
                    t.getName(),
                    projectNames,
                    departmentNames
            });
        }

        tblAddtask.setModel(model);

        // Ẩn cột ID
        tblAddtask.getColumnModel().getColumn(0).setMinWidth(0);
        tblAddtask.getColumnModel().getColumn(0).setMaxWidth(0);
        tblAddtask.getColumnModel().getColumn(0).setWidth(0);
    }


    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(() -> {
            AllTask dialog = new AllTask(new javax.swing.JFrame(), true);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lbKeywork;
    private javax.swing.JScrollPane scrAddtask;
    private javax.swing.JTable tblAddtask;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}