/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ra.View.holidays;

import com.ra.Controller.HolidayController;
import com.ra.DAO.Holiday.HolidayDAO;
import com.ra.Model.Entity.Holidays;

import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author thuyhoang
 */
public class AddHoliday extends JPanel {

    /**
     * Creates new form AddHoliday
     */

    private HolidayController holidayController = new HolidayController(new HolidayDAO());
    public AddHoliday() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new JLabel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        dcDate = new com.toedter.calendar.JDateChooser();
        txtName = new JTextField();
        txtDescription = new JTextField();
        btnSave = new JButton();

        jLabel4.setFont(new java.awt.Font("Kannada MN", 1, 24)); // NOI18N
        jLabel4.setText("List Holiday");

        jLabel1.setText("Choose Date: ");

        jLabel2.setText("Name:");

        jLabel3.setText("Description: ");

        btnSave.setBackground(new java.awt.Color(102, 255, 255));
        btnSave.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSave.setText("追加");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(203, 203, 203)
                                                .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 170, GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(135, 135, 135)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(36, 36, 36)
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtDescription, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtName)
                                                                .addComponent(dcDate, GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))))
                                .addContainerGap(193, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(dcDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtDescription, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(btnSave, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            // Lấy input
            String name = txtName.getText().trim();
            Date selectedDate = dcDate.getDate();
            String description = txtDescription.getText().trim();

            // Validate
            if (name.isEmpty()) {
                JOptionPane.showMessageDialog(this, "休日名は必須です！");
                return;
            }
            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "日付を選択してください！");
                return;
            }

            // Convert Date -> String YYYY-MM-DD
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateHoliday = sdf.format(selectedDate);

            // Tạo entity Holiday
            Holidays holiday = new Holidays();
            holiday.setName(name);
            holiday.setDateHoliday(dcDate.getDate());
            holiday.setDescription(description);

            // Gọi controller để lưu DB
            holidayController.createHoliday(holiday);

            JOptionPane.showMessageDialog(this, "休日を追加しました！");

            // Reset form
            txtName.setText("");
            txtDescription.setText("");
            dcDate.setDate(null);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnSave;
    private com.toedter.calendar.JDateChooser dcDate;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JTextField txtDescription;
    private JTextField txtName;
    // End of variables declaration//GEN-END:variables
}