/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ra.View.menu;

/**
 *
 * @author Admin
 */
public class AddMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddMenu.class.getName());

    /**
     * Creates new form AddMenu
     */
    public AddMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnlAddMenu = new javax.swing.JPanel();
        lbMenucode = new javax.swing.JLabel();
        txtMenucode = new javax.swing.JTextField();
        lbMenuname = new javax.swing.JLabel();
        txtMenuname = new javax.swing.JTextField();
        lbRole = new javax.swing.JLabel();
        chkEmployee = new javax.swing.JCheckBox();
        chkManager = new javax.swing.JCheckBox();
        chkAdmin = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("新メニュー作成");
        setPreferredSize(new java.awt.Dimension(600, 400));

        pnlAddMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddMenu.setPreferredSize(new java.awt.Dimension(600, 400));

        lbMenucode.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbMenucode.setText("メニューコード");

        txtMenucode.setText("jTextField1");

        lbMenuname.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbMenuname.setText("メニュー名");

        txtMenuname.setText("jTextField1");
        txtMenuname.addActionListener(this::txtMenunameActionPerformed);

        lbRole.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbRole.setText("ロール");

        chkEmployee.setText("EMPLOYEE");
        chkEmployee.addActionListener(this::chkEmployeeActionPerformed);

        chkManager.setText("MANAGER");
        chkManager.addActionListener(this::chkManagerActionPerformed);

        chkAdmin.setText("ADMIN");
        chkAdmin.addActionListener(this::chkAdminActionPerformed);

        btnCancel.setBackground(new java.awt.Color(255, 204, 153));
        btnCancel.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        btnCancel.setText("キャンセル");

        btnSave.setBackground(new java.awt.Color(186, 225, 186));
        btnSave.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        btnSave.setText("保存");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout pnlAddMenuLayout = new javax.swing.GroupLayout(pnlAddMenu);
        pnlAddMenu.setLayout(pnlAddMenuLayout);
        pnlAddMenuLayout.setHorizontalGroup(
                pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddMenuLayout.createSequentialGroup()
                                .addContainerGap(86, Short.MAX_VALUE)
                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlAddMenuLayout.createSequentialGroup()
                                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pnlAddMenuLayout.createSequentialGroup()
                                                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddMenuLayout.createSequentialGroup()
                                                                                .addComponent(chkEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddMenuLayout.createSequentialGroup()
                                                                                .addComponent(btnCancel)
                                                                                .addGap(34, 34, 34)))
                                                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnSave)
                                                                        .addComponent(chkManager, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(chkAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1))
                                        .addGroup(pnlAddMenuLayout.createSequentialGroup()
                                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(lbMenuname)
                                                        .addComponent(lbMenucode)
                                                        .addComponent(lbRole))
                                                .addGap(26, 26, 26)
                                                .addComponent(txtMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101))
        );
        pnlAddMenuLayout.setVerticalGroup(
                pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAddMenuLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkEmployee)
                                        .addComponent(chkManager, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chkAdmin))
                                .addGap(64, 64, 64)
                                .addGroup(pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCancel)
                                        .addComponent(btnSave))
                                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlAddMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void txtMenunameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void chkAdminActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void chkManagerActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void chkEmployeeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddMenu().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JCheckBox chkEmployee;
    private javax.swing.JCheckBox chkManager;
    private javax.swing.JLabel lbMenucode;
    private javax.swing.JLabel lbMenuname;
    private javax.swing.JLabel lbRole;
    private javax.swing.JPanel pnlAddMenu;
    private javax.swing.JTextField txtMenucode;
    private javax.swing.JTextField txtMenuname;
    // End of variables declaration
}
