package com.ra.View.menu;

import com.ra.Controller.PermissionController;
import com.ra.Controller.RoleController;
import com.ra.Model.Entity.Permission;
import com.ra.Model.Entity.Roles;

import javax.swing.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class AddMenu extends javax.swing.JPanel {

    // 1. KHAI BÁO CONTROLLER VÀ ENTITY
    private final PermissionController permissionController = new PermissionController();
    private final RoleController roleController = new RoleController();

    // permission đang sửa (null nếu là tạo mới)
    private Permission editingPermission = null;

    /**
     * Creates new form AddMenu1
     */
    public AddMenu() {
        initComponents();
        // Cài đặt sự kiện cho nút Cancel (đóng cửa sổ cha)
        btnCancel.addActionListener(e -> closeParentWindow());
    }

    // Constructor EDIT Mode (Dành cho việc tạo JPanel này trong chế độ chỉnh sửa)
    // Lưu ý: Cần gọi loadEditData() sau khi khởi tạo JPanel này.
    public AddMenu(Permission permission) {
        this.editingPermission = permission;
        initComponents();
        loadEditData();
        btnSave.setText("更新"); // Cập nhật chữ trên nút
        btnCancel.addActionListener(e -> closeParentWindow());
    }

    // Phương thức hỗ trợ đóng cửa sổ cha (JFrame/JDialog)
    private void closeParentWindow() {
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }

    // Phương thức tải dữ liệu chỉnh sửa
    private void loadEditData() {
        if (editingPermission == null) return;

        txtMenucode.setText(editingPermission.getCode());
        txtMenuname.setText(editingPermission.getName());

        if (editingPermission.getRoles() != null) {
            for (Roles r : editingPermission.getRoles()) {
                switch (r.getName()) {
                    case "EMPLOYEE" -> chkEmployee.setSelected(true);
                    case "MANAGER" -> chkManager.setSelected(true);
                    case "ADMIN" -> chkAdmin.setSelected(true);
                }
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        lbMenucode = new javax.swing.JLabel();
        txtMenucode = new javax.swing.JTextField();
        lbMenuname = new javax.swing.JLabel();
        txtMenuname = new javax.swing.JTextField();
        lbRole = new javax.swing.JLabel();
        chkEmployee = new javax.swing.JCheckBox();
        chkManager = new javax.swing.JCheckBox();
        chkAdmin = new javax.swing.JCheckBox();
        btnCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(186, 225, 186));
        btnSave.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        btnSave.setText("保存");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        lbMenucode.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbMenucode.setText("メニューコード");

        txtMenucode.setText("jTextField1");

        lbMenuname.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbMenuname.setText("メニュー名");

        txtMenuname.setText("jTextField1");
        txtMenuname.addActionListener(this::txtMenunameActionPerformed);

        lbRole.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbRole.setText("ロール");

        chkEmployee.setText("EMPLOYEE");
        chkEmployee.addActionListener(this::chkEmployeeActionPerformed);

        chkManager.setText("MANAGER");
        chkManager.addActionListener(this::chkManagerActionPerformed);

        chkAdmin.setText("ADMIN");
        chkAdmin.addActionListener(this::chkAdminActionPerformed);

        btnCancel.setBackground(new java.awt.Color(255, 204, 153));
        btnCancel.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        btnCancel.setText("キャンセル");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(chkEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCancel)
                                        .addGap(34, 34, 34)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSave)
                                    .addComponent(chkManager, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbMenuname)
                            .addComponent(lbMenucode)
                            .addComponent(lbRole))
                        .addGap(26, 26, 26)
                        .addComponent(txtMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMenucode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMenuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRole, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkEmployee)
                    .addComponent(chkManager, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdmin))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // ======================================================
    // SAVE HANDLER — CREATE + UPDATE
    // ======================================================
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String code = txtMenucode.getText().trim();
        String name = txtMenuname.getText().trim();

        if (code.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "コードと名前は必須です！");
            return;
        }

        // Lấy roles được chọn
        List<Roles> selectedRoles = new ArrayList<>();

        if (chkEmployee.isSelected()) {
            Optional<Roles> r = roleController.findByName("EMPLOYEE");
            r.ifPresent(selectedRoles::add);
        }
        if (chkManager.isSelected()) {
            Optional<Roles> r = roleController.findByName("MANAGER");
            r.ifPresent(selectedRoles::add);
        }
        if (chkAdmin.isSelected()) {
            Optional<Roles> r = roleController.findByName("ADMIN");
            r.ifPresent(selectedRoles::add);
        }


        // ========== CREATE ==========
        if (editingPermission == null) {

            Permission p = new Permission();
            p.setCode(code);
            p.setName(name);
            p.setRoles(selectedRoles);
            p.setCreatedAt(LocalDateTime.now());

            Permission saved = permissionController.create(p);

            if (saved != null) {
                JOptionPane.showMessageDialog(this, "メニューが作成されました！");
                closeParentWindow();
            } else {
                JOptionPane.showMessageDialog(this, "作成に失敗しました！", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        // ========== UPDATE ==========
        else {
            editingPermission.setCode(code);
            editingPermission.setName(name);
            editingPermission.setRoles(selectedRoles);
            editingPermission.setUpdatedAt(LocalDateTime.now());

            permissionController.update(editingPermission);

            JOptionPane.showMessageDialog(this, "メニューが更新されました！");
            closeParentWindow();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtMenunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMenunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMenunameActionPerformed

    private void chkEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEmployeeActionPerformed

    private void chkManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkManagerActionPerformed

    private void chkAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkAdmin;
    private javax.swing.JCheckBox chkEmployee;
    private javax.swing.JCheckBox chkManager;
    private javax.swing.JLabel lbMenucode;
    private javax.swing.JLabel lbMenuname;
    private javax.swing.JLabel lbRole;
    private javax.swing.JTextField txtMenucode;
    private javax.swing.JTextField txtMenuname;
    // End of variables declaration//GEN-END:variables

    // ======================================================
    // MAIN METHOD ĐỂ CHẠY THỬ
    // ======================================================
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Tạo và hiển thị form */
        java.awt.EventQueue.invokeLater(() -> {
            // Tạo một JFrame tạm thời để chứa JPanel AddMenu1
            JFrame frame = new JFrame("メニュー作成 (テスト)");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            // Thêm JPanel vào JFrame
            frame.add(new AddMenu());

            // Tự động điều chỉnh kích thước và hiển thị
            frame.pack();
            frame.setLocationRelativeTo(null); // Đặt ở giữa màn hình
            frame.setVisible(true);
        });
    }
}