
package com.ra.View.menu;

// Thêm import cần thiết cho ButtonRenderer và ButtonEditor
import com.ra.View.button.ButtonRenderer;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**^
 *
 * @author Admin
 */
public class AllMenu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AllMenu.class.getName());

    /**
     * Creates new form UserList
     */
    public AllMenu() {
        initComponents();

        // **********************************************
        // GỌI PHƯƠNG THỨC THIẾT LẬP CỘT NÚT
        // **********************************************
        setupButtonColumns(tblAllmenu);
        // tblAllmenu là tên biến JTable của bạn, đã được khởi tạo ở initComponents()
    }

    // *************************************************************
    // THÊM PHƯƠNG THỨC THIẾT LẬP CỘT NÚT (CODE CẦU NỐI)
    // *************************************************************
    private void setupButtonColumns(JTable table) {

        // === Cột 4: Chỉnh sửa (編集) ===
        // Index cột 3 (vì cột bắt đầu từ 0: 0, 1, 2, 3, 4)
        TableColumn editColumn = table.getColumnModel().getColumn(3);

        // Khởi tạo ButtonEditor và ButtonRenderer cho cột "編集"
        // LƯU Ý: Đảm bảo ButtonRenderer.java và ButtonEditor.java 
        // đã được đặt trong package com.ra.View.menu;

        // Renderer (Hiển thị nút)
        editColumn.setCellRenderer(new ButtonRenderer("編集"));


        // === Cột 5: Xóa (削除) ===
        TableColumn deleteColumn = table.getColumnModel().getColumn(4); // Index cột 4

        // Renderer (Hiển thị nút)
        deleteColumn.setCellRenderer(new ButtonRenderer("削除"));

        // Tùy chỉnh chiều rộng cột (Tùy chọn)
        editColumn.setPreferredWidth(60);
        deleteColumn.setPreferredWidth(60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnlAllmenu = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAllMenu = new javax.swing.JButton();
        btnAddmenu = new javax.swing.JButton();
        scrollPaneTable = new javax.swing.JScrollPane();
        tblAllmenu = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ユーザーリスト");
        setPreferredSize(new java.awt.Dimension(600, 400));

        pnlAllmenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlAllmenu.setPreferredSize(new java.awt.Dimension(600, 400));

        txtSearch.setText("jTextField1");
        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setBackground(new java.awt.Color(229, 229, 229));
        btnSearch.setText("検索");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnAllMenu.setText("すべて");
        btnAllMenu.addActionListener(this::btnAllMenuActionPerformed);

        btnAddmenu.setBackground(new java.awt.Color(208, 241, 208));
        btnAddmenu.setText("新メニュー作成");

        tblAllmenu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String [] {
                        "メニューコード", "メニュー名", "ロール", "編集", "削除"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblAllmenu.setCellSelectionEnabled(true);
        tblAllmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblAllmenu.setShowHorizontalLines(true);
        tblAllmenu.setShowVerticalLines(true);
        tblAllmenu.setSurrendersFocusOnKeystroke(true);
        scrollPaneTable.setViewportView(tblAllmenu);

        javax.swing.GroupLayout pnlAllmenuLayout = new javax.swing.GroupLayout(pnlAllmenu);
        pnlAllmenu.setLayout(pnlAllmenuLayout);
        pnlAllmenuLayout.setHorizontalGroup(
                pnlAllmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllmenuLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(pnlAllmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(scrollPaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                                        .addGroup(pnlAllmenuLayout.createSequentialGroup()
                                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnAllMenu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAddmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42))
        );
        pnlAllmenuLayout.setVerticalGroup(
                pnlAllmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAllmenuLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(pnlAllmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSearch)
                                        .addComponent(btnAllMenu)
                                        .addComponent(btnAddmenu))
                                .addGap(18, 18, 18)
                                .addComponent(scrollPaneTable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlAllmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlAllmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("UserList");

        pack();
    }// </editor-fold>

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnAllMenuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AllMenu().setVisible(true));
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnAddmenu;
    private javax.swing.JButton btnAllMenu;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel pnlAllmenu;
    private javax.swing.JScrollPane scrollPaneTable;
    private javax.swing.JTable tblAllmenu;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration
}
