package com.ra.View.dashboard;

//Thêm các imports cần thiết cho LoginScreen


// --------------- Import các JPanel mới bắt đầu -------------------------
import com.ra.Model.Entity.Users;
import com.ra.View.login.LoginScreen;
import com.ra.View.user.AddUser;
import com.ra.View.user.AllUser;
import com.ra.View.department.AddDepartment;
import com.ra.View.department.AllDepartment;
import com.ra.View.project.AddProject;
import com.ra.View.project.AllProject;
import com.ra.View.task.AddTask;
import com.ra.View.task.AllTask;
import com.ra.View.menu.AddMenu;
import com.ra.View.menu.AllMenu;
import com.ra.View.report.ReportSummaryPanel;
import com.ra.View.attendance.AddAttendance;
import com.ra.View.attendance.AttendanceDate;
import com.ra.View.attendance.AttendanceMonth;
import com.ra.View.holidays.AddHoliday;
import com.ra.View.holidays.AllHoliday;





// --------------- Import các JPanel mới kết thúc -------------------------



import java.time.ZonedDateTime; // Để lấy thời gian hiện tại
import java.time.format.DateTimeFormatter; // Để định dạng chuỗi
import java.util.Locale; // Để định dạng theo Locale Nhật Bản
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainDashboard extends javax.swing.JFrame {

    private Users currentUser;

    // 🌟 CONSTRUCTOR CHÍNH (ĐƯỢC GỌI TỪ LOGINSCREEN)
    public MainDashboard(Users user) {
        this.currentUser = user;
        initComponents();
        applyRoleAccess();
        startClock();


    }

    // 🌟 SỬA PHƯƠNG THỨC applyRoleAccess ĐỂ XỬ LÝ NULL AN TOÀN
    private void applyRoleAccess() {
        int roleId = currentUser.getRole().getId();

        System.out.println("ROLE APPLY => " + roleId);
        //tạm thời

        switch (roleId) {
            case 3: // ADMIN
                // Admin xem tất cả
                pnlMenuHeader.setVisible(false);
                break;

            case 2: // MANAGER

                pnlMenuHeader.setVisible(false);
                pnlProjectHeader.setVisible(false);
                pnlDepartmentHeader.setVisible(false);
                pnlTaskHeader.setVisible(false);
                pnlHolidayHeader.setVisible(false);
                break;

            case 1: // EMPLOYEE
                pnlUserHeader.setVisible(false);
                pnlDepartmentHeader.setVisible(false);
                pnlProjectHeader.setVisible(false);
                pnlMenuHeader.setVisible(false);
                pnlTaskHeader.setVisible(false);
                pnlHolidayHeader.setVisible(false);
                pnlAttendanceMonth.setVisible(false);
                pnlReport.setVisible(false);
                break;
        }
    }


    // ---------- Thêm phương thức showPanel -----------------
    private void showPanel(javax.swing.JPanel panel) {

        // 1. Xóa tất cả các component hiện có trong Working Area
        pnlWorkingArea.removeAll();

        // 2. Thiết lập Layout cho Working Area (quan trọng)
        pnlWorkingArea.setLayout(new java.awt.BorderLayout());

        // 3. Thêm JPanel mới vào Working Area
        pnlWorkingArea.add(panel, java.awt.BorderLayout.CENTER);

        // 4. Cập nhật giao diện để hiển thị Panel mới
        pnlWorkingArea.revalidate();
        pnlWorkingArea.repaint();
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());


    // 🌟 CONSTRUCTOR MẶC ĐỊNH
    public MainDashboard() {
        this(null); // Gọi constructor chính với User là null để không bị lỗi
    }



    private String getCurrentDateTimeJapan() {
        ZonedDateTime now = ZonedDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter
                .ofPattern("yyyy/MM/dd(E) HH:mm:ss")
                .withLocale(Locale.JAPAN);
        return now.format(formatter);
    }

    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbDatetime.setText(getCurrentDateTimeJapan());
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        pnlHeaderSidebar = new javax.swing.JPanel();
        lbHeaderSidebar = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        pnlUserHeader = new javax.swing.JPanel();
        UserHeader = new javax.swing.JButton();
        pnlUsermenu = new javax.swing.JPanel();
        pnlAddUser = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        pnlAllUser = new javax.swing.JPanel();
        btnAllUser = new javax.swing.JButton();
        pnlDepartmentHeader = new javax.swing.JPanel();
        btnDepartmentHeader = new javax.swing.JButton();
        pnlDepartmentmenu = new javax.swing.JPanel();
        pnlAddDepartment = new javax.swing.JPanel();
        btnAddDepartment = new javax.swing.JButton();
        pnlAllDeparment = new javax.swing.JPanel();
        btnAllDepartment = new javax.swing.JButton();
        pnlProjectHeader = new javax.swing.JPanel();
        btnProjectHeader = new javax.swing.JButton();
        pnlProjectmenu = new javax.swing.JPanel();
        pnlAddProject = new javax.swing.JPanel();
        btnAddProject = new javax.swing.JButton();
        pnlAllProject = new javax.swing.JPanel();
        btnAllProject = new javax.swing.JButton();
        pnlTaskHeader = new javax.swing.JPanel();
        btnTaskHeader = new javax.swing.JButton();
        pnlTaskmenu = new javax.swing.JPanel();
        pnlAddTask = new javax.swing.JPanel();
        btnAddTask = new javax.swing.JButton();
        pnlAllTask = new javax.swing.JPanel();
        btnAllTask = new javax.swing.JButton();
        pnlAttendanceHeader = new javax.swing.JPanel();
        btnTaskHeader1 = new javax.swing.JButton();
        pnlAttendancemenu = new javax.swing.JPanel();
        pnlAddAttendance = new javax.swing.JPanel();
        btnAddAttendance = new javax.swing.JButton();
        pnlAttendanceMonth = new javax.swing.JPanel();
        btnViewAttendanceMonth = new javax.swing.JButton();
        pnlAttendanceDay = new javax.swing.JPanel();
        btnViewAttendanceDay = new javax.swing.JButton();
        pnlReport = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        pnlHolidayHeader = new javax.swing.JPanel();
        btnHolidayHeader = new javax.swing.JButton();
        pnlHolidaymenu = new javax.swing.JPanel();
        pnlAddHoliday = new javax.swing.JPanel();
        btnAddMenu1 = new javax.swing.JButton();
        pnlAllHoliday = new javax.swing.JPanel();
        btnAllMenu1 = new javax.swing.JButton();
        pnlMenuHeader = new javax.swing.JPanel();
        btnMenuHeader = new javax.swing.JButton();
        pnlMenumenu = new javax.swing.JPanel();
        pnlAddMenu = new javax.swing.JPanel();
        btnAddMenu = new javax.swing.JButton();
        pnlAllMenu = new javax.swing.JPanel();
        btnAllMenu = new javax.swing.JButton();
        pnlLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        pnlMainContent = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbDatetime = new javax.swing.JLabel();
        pnlWorkingArea = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ダッシュボード");
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));

        pnlSidebar.setBackground(new java.awt.Color(0, 0, 0));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(250, 300));
        pnlSidebar.setLayout(new javax.swing.BoxLayout(pnlSidebar, javax.swing.BoxLayout.Y_AXIS));

        pnlHeaderSidebar.setBackground(new java.awt.Color(0, 51, 51));
        pnlHeaderSidebar.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlHeaderSidebar.setPreferredSize(new java.awt.Dimension(202, 40));
        pnlHeaderSidebar.setLayout(new java.awt.GridBagLayout());

        lbHeaderSidebar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lbHeaderSidebar.setForeground(new java.awt.Color(255, 255, 255));
        lbHeaderSidebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeaderSidebar.setText("勤怠管理システム");
        lbHeaderSidebar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeaderSidebar.add(lbHeaderSidebar, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlHeaderSidebar);

        pnlDashboard.setBackground(new java.awt.Color(0, 0, 0));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDashboard.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDashboard.setPreferredSize(new java.awt.Dimension(250, 30));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 102));
        btnDashboard.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("ダッシュボード");
        btnDashboard.setMaximumSize(new java.awt.Dimension(250, 30));
        btnDashboard.setMinimumSize(new java.awt.Dimension(250, 30));
        btnDashboard.setPreferredSize(new java.awt.Dimension(250, 30));
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSidebar.add(pnlDashboard);

        pnlUserHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlUserHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlUserHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlUserHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlUserHeader.setPreferredSize(new java.awt.Dimension(250, 30));

        UserHeader.setBackground(new java.awt.Color(0, 0, 102));
        UserHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        UserHeader.setForeground(new java.awt.Color(255, 255, 255));
        UserHeader.setText("ユーザー管理");
        UserHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        UserHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        UserHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        UserHeader.addActionListener(this::UserHeaderActionPerformed);

        javax.swing.GroupLayout pnlUserHeaderLayout = new javax.swing.GroupLayout(pnlUserHeader);
        pnlUserHeader.setLayout(pnlUserHeaderLayout);
        pnlUserHeaderLayout.setHorizontalGroup(
            pnlUserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlUserHeaderLayout.setVerticalGroup(
            pnlUserHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserHeaderLayout.createSequentialGroup()
                .addComponent(UserHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlUserHeader);

        pnlUsermenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlUsermenu.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlUsermenu.setVisible(false);
        pnlUsermenu.setLayout(new javax.swing.BoxLayout(pnlUsermenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddUser.setBackground(new java.awt.Color(0, 102, 153));
        pnlAddUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddUser.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddUser.setBackground(new java.awt.Color(0, 102, 102));
        btnAddUser.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("新ユーザー作成");
        btnAddUser.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddUser.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddUser.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddUser.addActionListener(this::btnAddUserActionPerformed);

        javax.swing.GroupLayout pnlAddUserLayout = new javax.swing.GroupLayout(pnlAddUser);
        pnlAddUser.setLayout(pnlAddUserLayout);
        pnlAddUserLayout.setHorizontalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddUserLayout.setVerticalGroup(
            pnlAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlUsermenu.add(pnlAddUser);

        pnlAllUser.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllUser.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllUser.setBackground(new java.awt.Color(0, 102, 102));
        btnAllUser.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAllUser.setText("ユーザーリスト");
        btnAllUser.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllUser.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllUser.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllUser.addActionListener(this::btnAllUserActionPerformed);

        javax.swing.GroupLayout pnlAllUserLayout = new javax.swing.GroupLayout(pnlAllUser);
        pnlAllUser.setLayout(pnlAllUserLayout);
        pnlAllUserLayout.setHorizontalGroup(
            pnlAllUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllUserLayout.setVerticalGroup(
            pnlAllUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlUsermenu.add(pnlAllUser);

        pnlSidebar.add(pnlUsermenu);

        pnlDepartmentHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlDepartmentHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDepartmentHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlDepartmentHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDepartmentHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlDepartmentHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlDepartmentHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDepartmentHeaderMouseClicked(evt);
            }
        });

        btnDepartmentHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnDepartmentHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnDepartmentHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnDepartmentHeader.setText("部署管理");
        btnDepartmentHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        btnDepartmentHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        btnDepartmentHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        btnDepartmentHeader.addActionListener(this::btnDepartmentHeaderActionPerformed);

        javax.swing.GroupLayout pnlDepartmentHeaderLayout = new javax.swing.GroupLayout(pnlDepartmentHeader);
        pnlDepartmentHeader.setLayout(pnlDepartmentHeaderLayout);
        pnlDepartmentHeaderLayout.setHorizontalGroup(
            pnlDepartmentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDepartmentHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDepartmentHeaderLayout.setVerticalGroup(
            pnlDepartmentHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDepartmentHeaderLayout.createSequentialGroup()
                .addComponent(btnDepartmentHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlDepartmentHeader);

        pnlDepartmentmenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlDepartmentmenu.setVisible(false);
        pnlDepartmentmenu.setLayout(new javax.swing.BoxLayout(pnlDepartmentmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddDepartment.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddDepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddDepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddDepartment.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddDepartment.setBackground(new java.awt.Color(0, 102, 102));
        btnAddDepartment.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDepartment.setText("新部署作成");
        btnAddDepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddDepartment.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddDepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddDepartment.addActionListener(this::btnAddDepartmentActionPerformed);

        javax.swing.GroupLayout pnlAddDepartmentLayout = new javax.swing.GroupLayout(pnlAddDepartment);
        pnlAddDepartment.setLayout(pnlAddDepartmentLayout);
        pnlAddDepartmentLayout.setHorizontalGroup(
            pnlAddDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddDepartmentLayout.setVerticalGroup(
            pnlAddDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlDepartmentmenu.add(pnlAddDepartment);

        pnlAllDeparment.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllDeparment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllDeparment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllDeparment.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllDepartment.setBackground(new java.awt.Color(0, 102, 102));
        btnAllDepartment.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllDepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAllDepartment.setText("部署リスト");
        btnAllDepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllDepartment.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllDepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllDepartment.addActionListener(this::btnAllDepartmentActionPerformed);

        javax.swing.GroupLayout pnlAllDeparmentLayout = new javax.swing.GroupLayout(pnlAllDeparment);
        pnlAllDeparment.setLayout(pnlAllDeparmentLayout);
        pnlAllDeparmentLayout.setHorizontalGroup(
            pnlAllDeparmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllDeparmentLayout.setVerticalGroup(
            pnlAllDeparmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlDepartmentmenu.add(pnlAllDeparment);

        pnlSidebar.add(pnlDepartmentmenu);

        pnlProjectHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlProjectHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlProjectHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlProjectHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProjectHeaderMouseClicked(evt);
            }
        });

        btnProjectHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnProjectHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnProjectHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnProjectHeader.setText("プロジェクト管理");
        btnProjectHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        btnProjectHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        btnProjectHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        btnProjectHeader.addActionListener(this::btnProjectHeaderActionPerformed);

        javax.swing.GroupLayout pnlProjectHeaderLayout = new javax.swing.GroupLayout(pnlProjectHeader);
        pnlProjectHeader.setLayout(pnlProjectHeaderLayout);
        pnlProjectHeaderLayout.setHorizontalGroup(
            pnlProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProjectHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlProjectHeaderLayout.setVerticalGroup(
            pnlProjectHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectHeaderLayout.createSequentialGroup()
                .addComponent(btnProjectHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlProjectHeader);

        pnlProjectmenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlProjectmenu.setVisible(false);
        pnlProjectmenu.setLayout(new javax.swing.BoxLayout(pnlProjectmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddProject.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddProject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddProject.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddProject.setBackground(new java.awt.Color(0, 102, 102));
        btnAddProject.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddProject.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProject.setText("新プロジェクト作成");
        btnAddProject.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddProject.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddProject.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddProject.addActionListener(this::btnAddProjectActionPerformed);

        javax.swing.GroupLayout pnlAddProjectLayout = new javax.swing.GroupLayout(pnlAddProject);
        pnlAddProject.setLayout(pnlAddProjectLayout);
        pnlAddProjectLayout.setHorizontalGroup(
            pnlAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddProjectLayout.setVerticalGroup(
            pnlAddProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlProjectmenu.add(pnlAddProject);

        pnlAllProject.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllProject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllProject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllProject.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllProject.setBackground(new java.awt.Color(0, 102, 102));
        btnAllProject.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllProject.setForeground(new java.awt.Color(255, 255, 255));
        btnAllProject.setText("プロジェクトリスト");
        btnAllProject.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllProject.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllProject.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllProject.addActionListener(this::btnAllProjectActionPerformed);

        javax.swing.GroupLayout pnlAllProjectLayout = new javax.swing.GroupLayout(pnlAllProject);
        pnlAllProject.setLayout(pnlAllProjectLayout);
        pnlAllProjectLayout.setHorizontalGroup(
            pnlAllProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllProjectLayout.setVerticalGroup(
            pnlAllProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlProjectmenu.add(pnlAllProject);

        pnlSidebar.add(pnlProjectmenu);

        pnlTaskHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlTaskHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTaskHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlTaskHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaskHeaderMouseClicked(evt);
            }
        });

        btnTaskHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnTaskHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnTaskHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnTaskHeader.setText("タスク管理");
        btnTaskHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        btnTaskHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        btnTaskHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        btnTaskHeader.addActionListener(this::btnTaskHeaderActionPerformed);

        javax.swing.GroupLayout pnlTaskHeaderLayout = new javax.swing.GroupLayout(pnlTaskHeader);
        pnlTaskHeader.setLayout(pnlTaskHeaderLayout);
        pnlTaskHeaderLayout.setHorizontalGroup(
            pnlTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTaskHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTaskHeaderLayout.setVerticalGroup(
            pnlTaskHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaskHeaderLayout.createSequentialGroup()
                .addComponent(btnTaskHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlTaskHeader);

        pnlTaskmenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlTaskmenu.setVisible(false);
        pnlTaskmenu.setLayout(new javax.swing.BoxLayout(pnlTaskmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddTask.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddTask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddTask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddTask.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddTask.setBackground(new java.awt.Color(0, 102, 102));
        btnAddTask.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddTask.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTask.setText("新タスク作成");
        btnAddTask.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddTask.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddTask.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddTask.addActionListener(this::btnAddTaskActionPerformed);

        javax.swing.GroupLayout pnlAddTaskLayout = new javax.swing.GroupLayout(pnlAddTask);
        pnlAddTask.setLayout(pnlAddTaskLayout);
        pnlAddTaskLayout.setHorizontalGroup(
            pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddTaskLayout.setVerticalGroup(
            pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTaskmenu.add(pnlAddTask);

        pnlAllTask.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllTask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllTask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllTask.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllTask.setBackground(new java.awt.Color(0, 102, 102));
        btnAllTask.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllTask.setForeground(new java.awt.Color(255, 255, 255));
        btnAllTask.setText("タスクリスト");
        btnAllTask.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllTask.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllTask.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllTask.addActionListener(this::btnAllTaskActionPerformed);

        javax.swing.GroupLayout pnlAllTaskLayout = new javax.swing.GroupLayout(pnlAllTask);
        pnlAllTask.setLayout(pnlAllTaskLayout);
        pnlAllTaskLayout.setHorizontalGroup(
            pnlAllTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllTaskLayout.setVerticalGroup(
            pnlAllTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlTaskmenu.add(pnlAllTask);

        pnlSidebar.add(pnlTaskmenu);

        pnlAttendanceHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlAttendanceHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlAttendanceHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlAttendanceHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAttendanceHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAttendanceHeaderMouseClicked(evt);
            }
        });

        btnTaskHeader1.setBackground(new java.awt.Color(0, 0, 102));
        btnTaskHeader1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnTaskHeader1.setForeground(new java.awt.Color(255, 255, 255));
        btnTaskHeader1.setText("勤怠管理");
        btnTaskHeader1.setMaximumSize(new java.awt.Dimension(250, 30));
        btnTaskHeader1.setMinimumSize(new java.awt.Dimension(250, 30));
        btnTaskHeader1.setPreferredSize(new java.awt.Dimension(250, 30));
        btnTaskHeader1.addActionListener(this::btnTaskHeader1ActionPerformed);

        javax.swing.GroupLayout pnlAttendanceHeaderLayout = new javax.swing.GroupLayout(pnlAttendanceHeader);
        pnlAttendanceHeader.setLayout(pnlAttendanceHeaderLayout);
        pnlAttendanceHeaderLayout.setHorizontalGroup(
            pnlAttendanceHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTaskHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAttendanceHeaderLayout.setVerticalGroup(
            pnlAttendanceHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAttendanceHeaderLayout.createSequentialGroup()
                .addComponent(btnTaskHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlAttendanceHeader);

        pnlAttendancemenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlAttendancemenu.setMaximumSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setMinimumSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setPreferredSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setVisible(false);
        pnlAttendancemenu.setLayout(new javax.swing.BoxLayout(pnlAttendancemenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddAttendance.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddAttendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddAttendance.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddAttendance.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddAttendance.setBackground(new java.awt.Color(0, 102, 102));
        btnAddAttendance.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddAttendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAddAttendance.setText("勤務登録");
        btnAddAttendance.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddAttendance.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddAttendance.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddAttendance.addActionListener(this::btnAddAttendanceActionPerformed);

        javax.swing.GroupLayout pnlAddAttendanceLayout = new javax.swing.GroupLayout(pnlAddAttendance);
        pnlAddAttendance.setLayout(pnlAddAttendanceLayout);
        pnlAddAttendanceLayout.setHorizontalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddAttendance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddAttendanceLayout.setVerticalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddAttendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAttendancemenu.add(pnlAddAttendance);

        pnlAttendanceMonth.setBackground(new java.awt.Color(0, 51, 153));
        pnlAttendanceMonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAttendanceMonth.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceMonth.setPreferredSize(new java.awt.Dimension(250, 30));

        btnViewAttendanceMonth.setBackground(new java.awt.Color(0, 102, 102));
        btnViewAttendanceMonth.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnViewAttendanceMonth.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAttendanceMonth.setText("月別確認");
        btnViewAttendanceMonth.setMaximumSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceMonth.setMinimumSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceMonth.setPreferredSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceMonth.addActionListener(this::btnViewAttendanceMonthActionPerformed);

        javax.swing.GroupLayout pnlAttendanceMonthLayout = new javax.swing.GroupLayout(pnlAttendanceMonth);
        pnlAttendanceMonth.setLayout(pnlAttendanceMonthLayout);
        pnlAttendanceMonthLayout.setHorizontalGroup(
            pnlAttendanceMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewAttendanceMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAttendanceMonthLayout.setVerticalGroup(
            pnlAttendanceMonthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewAttendanceMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAttendancemenu.add(pnlAttendanceMonth);

        pnlAttendanceDay.setBackground(new java.awt.Color(0, 51, 153));
        pnlAttendanceDay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAttendanceDay.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceDay.setPreferredSize(new java.awt.Dimension(250, 30));

        btnViewAttendanceDay.setBackground(new java.awt.Color(0, 102, 102));
        btnViewAttendanceDay.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnViewAttendanceDay.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAttendanceDay.setText("日別詳細確認");
        btnViewAttendanceDay.setMaximumSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceDay.setMinimumSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceDay.setPreferredSize(new java.awt.Dimension(250, 30));
        btnViewAttendanceDay.addActionListener(this::btnViewAttendanceDayActionPerformed);

        javax.swing.GroupLayout pnlAttendanceDayLayout = new javax.swing.GroupLayout(pnlAttendanceDay);
        pnlAttendanceDay.setLayout(pnlAttendanceDayLayout);
        pnlAttendanceDayLayout.setHorizontalGroup(
            pnlAttendanceDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewAttendanceDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAttendanceDayLayout.setVerticalGroup(
            pnlAttendanceDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnViewAttendanceDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAttendancemenu.add(pnlAttendanceDay);

        pnlSidebar.add(pnlAttendancemenu);

        pnlReport.setBackground(new java.awt.Color(0, 0, 0));
        pnlReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlReport.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlReport.setMinimumSize(new java.awt.Dimension(250, 30));
        pnlReport.setPreferredSize(new java.awt.Dimension(250, 30));

        btnReport.setBackground(new java.awt.Color(0, 0, 102));
        btnReport.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setText("レポート");
        btnReport.setMaximumSize(new java.awt.Dimension(250, 30));
        btnReport.setMinimumSize(new java.awt.Dimension(250, 30));
        btnReport.setPreferredSize(new java.awt.Dimension(250, 30));
        btnReport.addActionListener(this::btnReportActionPerformed);

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSidebar.add(pnlReport);

        pnlHolidayHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlHolidayHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlHolidayHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlHolidayHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlHolidayHeader.setPreferredSize(new java.awt.Dimension(254, 30));
        pnlHolidayHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHolidayHeaderMouseClicked(evt);
            }
        });

        btnHolidayHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnHolidayHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnHolidayHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnHolidayHeader.setText("休日");
        btnHolidayHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        btnHolidayHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        btnHolidayHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        btnHolidayHeader.addActionListener(this::btnHolidayHeaderActionPerformed);

        javax.swing.GroupLayout pnlHolidayHeaderLayout = new javax.swing.GroupLayout(pnlHolidayHeader);
        pnlHolidayHeader.setLayout(pnlHolidayHeaderLayout);
        pnlHolidayHeaderLayout.setHorizontalGroup(
            pnlHolidayHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnHolidayHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHolidayHeaderLayout.setVerticalGroup(
            pnlHolidayHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHolidayHeaderLayout.createSequentialGroup()
                .addComponent(btnHolidayHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlHolidayHeader);

        pnlHolidaymenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlHolidaymenu.setVisible(false);
        pnlHolidaymenu.setLayout(new javax.swing.BoxLayout(pnlHolidaymenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddHoliday.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddHoliday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddHoliday.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddHoliday.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddMenu1.setBackground(new java.awt.Color(0, 102, 102));
        btnAddMenu1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMenu1.setText("新休日作成");
        btnAddMenu1.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddMenu1.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddMenu1.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddMenu1.addActionListener(this::btnAddMenu1ActionPerformed);

        javax.swing.GroupLayout pnlAddHolidayLayout = new javax.swing.GroupLayout(pnlAddHoliday);
        pnlAddHoliday.setLayout(pnlAddHolidayLayout);
        pnlAddHolidayLayout.setHorizontalGroup(
            pnlAddHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddHolidayLayout.setVerticalGroup(
            pnlAddHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlHolidaymenu.add(pnlAddHoliday);

        pnlAllHoliday.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllHoliday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllHoliday.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllHoliday.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllMenu1.setBackground(new java.awt.Color(0, 102, 102));
        btnAllMenu1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnAllMenu1.setText("休日リスト");
        btnAllMenu1.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllMenu1.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllMenu1.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllMenu1.addActionListener(this::btnAllMenu1ActionPerformed);

        javax.swing.GroupLayout pnlAllHolidayLayout = new javax.swing.GroupLayout(pnlAllHoliday);
        pnlAllHoliday.setLayout(pnlAllHolidayLayout);
        pnlAllHolidayLayout.setHorizontalGroup(
            pnlAllHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllHolidayLayout.setVerticalGroup(
            pnlAllHolidayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllMenu1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlHolidaymenu.add(pnlAllHoliday);

        pnlSidebar.add(pnlHolidaymenu);

        pnlMenuHeader.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenuHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlMenuHeader.setPreferredSize(new java.awt.Dimension(254, 30));
        pnlMenuHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuHeaderMouseClicked(evt);
            }
        });

        btnMenuHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnMenuHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuHeader.setText("メニュー");
        btnMenuHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        btnMenuHeader.setMinimumSize(new java.awt.Dimension(250, 30));
        btnMenuHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        btnMenuHeader.addActionListener(this::btnMenuHeaderActionPerformed);

        javax.swing.GroupLayout pnlMenuHeaderLayout = new javax.swing.GroupLayout(pnlMenuHeader);
        pnlMenuHeader.setLayout(pnlMenuHeaderLayout);
        pnlMenuHeaderLayout.setHorizontalGroup(
            pnlMenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMenuHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuHeaderLayout.setVerticalGroup(
            pnlMenuHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuHeaderLayout.createSequentialGroup()
                .addComponent(btnMenuHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pnlSidebar.add(pnlMenuHeader);

        pnlMenumenu.setBackground(new java.awt.Color(0, 0, 0));
        pnlMenumenu.setVisible(false);
        pnlMenumenu.setLayout(new javax.swing.BoxLayout(pnlMenumenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddMenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddMenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddMenu.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAddMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnAddMenu.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAddMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMenu.setText("新メニュー作成");
        btnAddMenu.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAddMenu.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAddMenu.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAddMenu.addActionListener(this::btnAddMenuActionPerformed);

        javax.swing.GroupLayout pnlAddMenuLayout = new javax.swing.GroupLayout(pnlAddMenu);
        pnlAddMenu.setLayout(pnlAddMenuLayout);
        pnlAddMenuLayout.setHorizontalGroup(
            pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAddMenuLayout.setVerticalGroup(
            pnlAddMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAddMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlMenumenu.add(pnlAddMenu);

        pnlAllMenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllMenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllMenu.setPreferredSize(new java.awt.Dimension(250, 30));

        btnAllMenu.setBackground(new java.awt.Color(0, 102, 102));
        btnAllMenu.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAllMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAllMenu.setText("メニューリスト");
        btnAllMenu.setMaximumSize(new java.awt.Dimension(250, 30));
        btnAllMenu.setMinimumSize(new java.awt.Dimension(250, 30));
        btnAllMenu.setPreferredSize(new java.awt.Dimension(250, 30));
        btnAllMenu.addActionListener(this::btnAllMenuActionPerformed);

        javax.swing.GroupLayout pnlAllMenuLayout = new javax.swing.GroupLayout(pnlAllMenu);
        pnlAllMenu.setLayout(pnlAllMenuLayout);
        pnlAllMenuLayout.setHorizontalGroup(
            pnlAllMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAllMenuLayout.setVerticalGroup(
            pnlAllMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnAllMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlMenumenu.add(pnlAllMenu);

        pnlSidebar.add(pnlMenumenu);

        // CHÈN DÒNG CODE GLUE - Gắn Panel Logout xuống cuối Sidebar
        pnlSidebar.add(javax.swing.Box.createVerticalGlue());

        pnlLogout.setBackground(new java.awt.Color(0, 0, 0));
        pnlLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlLogout.setMaximumSize(new java.awt.Dimension(250, 30));

        btnLogout.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnLogout.setText("ログアウト");
        btnLogout.setMaximumSize(new java.awt.Dimension(250, 30));
        btnLogout.setMinimumSize(new java.awt.Dimension(250, 30));
        btnLogout.setPreferredSize(new java.awt.Dimension(250, 30));
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout pnlLogoutLayout = new javax.swing.GroupLayout(pnlLogout);
        pnlLogout.setLayout(pnlLogoutLayout);
        pnlLogoutLayout.setHorizontalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlLogoutLayout.setVerticalGroup(
            pnlLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlSidebar.add(pnlLogout);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlMainContent.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(228, 223, 223));
        pnlHeader.setMaximumSize(new java.awt.Dimension(32767, 42));
        pnlHeader.setPreferredSize(new java.awt.Dimension(100, 42));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lbDatetime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDatetime.setText("jLabel3");
        lbDatetime.setMaximumSize(new java.awt.Dimension(200, 60));
        lbDatetime.setPreferredSize(new java.awt.Dimension(250, 42));
        pnlHeader.add(lbDatetime, java.awt.BorderLayout.LINE_END);

        pnlMainContent.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlWorkingArea.setBackground(new java.awt.Color(255, 255, 255));
        pnlWorkingArea.setLayout(new java.awt.CardLayout());
        pnlMainContent.add(pnlWorkingArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnDashboardActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void UserHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_UserHeaderActionPerformed
        pnlUsermenu.setVisible(!pnlUsermenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_UserHeaderActionPerformed

    private void btnAllUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllUserActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllUser());
    }//GEN-LAST:event_btnAllUserActionPerformed

    private void btnAddUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddUser());
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnDepartmentHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnDepartmentHeaderActionPerformed
        pnlDepartmentmenu.setVisible(!pnlDepartmentmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnDepartmentHeaderActionPerformed

    private void pnlDepartmentHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDepartmentHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlDepartmentHeaderMouseClicked

    private void btnAddDepartmentActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddDepartment());
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnAllDepartmentActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllDepartmentActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllDepartment());
    }//GEN-LAST:event_btnAllDepartmentActionPerformed

    private void btnProjectHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnProjectHeaderActionPerformed
        pnlProjectmenu.setVisible(!pnlProjectmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnProjectHeaderActionPerformed

    private void pnlProjectHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProjectHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlProjectHeaderMouseClicked

    private void btnAddProjectActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddProjectActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddProject());
    }//GEN-LAST:event_btnAddProjectActionPerformed

    private void btnAllProjectActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllProjectActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllProject());
    }//GEN-LAST:event_btnAllProjectActionPerformed

    private void btnTaskHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnTaskHeaderActionPerformed
        pnlTaskmenu.setVisible(!pnlTaskmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnTaskHeaderActionPerformed

    private void pnlTaskHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaskHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlTaskHeaderMouseClicked

    private void btnAddTaskActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddTask());
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnAllTaskActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllTaskActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllTask());
    }//GEN-LAST:event_btnAllTaskActionPerformed

    private void btnTaskHeader1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnTaskHeader1ActionPerformed
        pnlAttendancemenu.setVisible(!pnlAttendancemenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnTaskHeader1ActionPerformed

    private void pnlAttendanceHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAttendanceHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlAttendanceHeaderMouseClicked

    private void btnAddAttendanceActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddAttendanceActionPerformed
        // 1. Lấy thông tin người dùng đang đăng nhập từ trường 'currentUser'
        Users userToPass = this.currentUser;

        // 2. Gọi constructor có tham số và truyền đối tượng Users vào
        AddAttendance addAttendancePanel = new AddAttendance(userToPass);

        // 3. Gọi phương thức showPanel (thực hiện xóa panel cũ, thêm panel mới, revalidate/repaint)
        showPanel(addAttendancePanel);
    }//GEN-LAST:event_btnAddAttendanceActionPerformed

    private void btnViewAttendanceMonthActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnViewAttendanceMonthActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AttendanceMonth());
    }//GEN-LAST:event_btnViewAttendanceMonthActionPerformed

    private void btnViewAttendanceDayActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnViewAttendanceDayActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AttendanceDate());
    }//GEN-LAST:event_btnViewAttendanceDayActionPerformed

    private void btnReportActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new ReportSummaryPanel());
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnMenuHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnMenuHeaderActionPerformed
        pnlMenumenu.setVisible(!pnlMenumenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnMenuHeaderActionPerformed

    private void pnlMenuHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlMenuHeaderMouseClicked

    private void btnAddMenuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddMenuActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddMenu());
    }//GEN-LAST:event_btnAddMenuActionPerformed

    private void btnAllMenuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllMenuActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllMenu());
    }//GEN-LAST:event_btnAllMenuActionPerformed


    private void btnHolidayHeaderActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnHolidayHeaderActionPerformed
        pnlHolidaymenu.setVisible(!pnlHolidaymenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }//GEN-LAST:event_btnHolidayHeaderActionPerformed

    private void pnlHolidayHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHolidayHeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlHolidayHeaderMouseClicked

    private void btnAddMenu1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAddMenu1ActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AddHoliday());
    }//GEN-LAST:event_btnAddMenu1ActionPerformed

    private void btnAllMenu1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnAllMenu1ActionPerformed
        // Gọi phương thức showPanel và truyền vào JPanel
        showPanel(new AllHoliday());
    }//GEN-LAST:event_btnAllMenu1ActionPerformed

    private void btnLogoutActionPerformed(ActionEvent evt) {

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "ログアウトしますか？",
                "確認",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {

            // Đóng Dashboard trước
            this.dispose();

            // Mở lại LoginScreen
            java.awt.EventQueue.invokeLater(() -> {
                new LoginScreen().setVisible(true);
            });
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton UserHeader;
    private javax.swing.JButton btnAddAttendance;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddMenu;
    private javax.swing.JButton btnAddMenu1;
    private javax.swing.JButton btnAddProject;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAllDepartment;
    private javax.swing.JButton btnAllMenu;
    private javax.swing.JButton btnAllMenu1;
    private javax.swing.JButton btnAllProject;
    private javax.swing.JButton btnAllTask;
    private javax.swing.JButton btnAllUser;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDepartmentHeader;
    private javax.swing.JButton btnHolidayHeader;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuHeader;
    private javax.swing.JButton btnProjectHeader;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTaskHeader;
    private javax.swing.JButton btnTaskHeader1;
    private javax.swing.JButton btnViewAttendanceDay;
    private javax.swing.JButton btnViewAttendanceMonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbDatetime;
    private javax.swing.JLabel lbHeaderSidebar;
    private javax.swing.JPanel pnlAddAttendance;
    private javax.swing.JPanel pnlAddDepartment;
    private javax.swing.JPanel pnlAddHoliday;
    private javax.swing.JPanel pnlAddMenu;
    private javax.swing.JPanel pnlAddProject;
    private javax.swing.JPanel pnlAddTask;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlAllDeparment;
    private javax.swing.JPanel pnlAllHoliday;
    private javax.swing.JPanel pnlAllMenu;
    private javax.swing.JPanel pnlAllProject;
    private javax.swing.JPanel pnlAllTask;
    private javax.swing.JPanel pnlAllUser;
    private javax.swing.JPanel pnlAttendanceDay;
    private javax.swing.JPanel pnlAttendanceHeader;
    private javax.swing.JPanel pnlAttendanceMonth;
    private javax.swing.JPanel pnlAttendancemenu;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDepartmentHeader;
    private javax.swing.JPanel pnlDepartmentmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderSidebar;
    private javax.swing.JPanel pnlHolidayHeader;
    private javax.swing.JPanel pnlHolidaymenu;
    private javax.swing.JPanel pnlLogout;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlMenuHeader;
    private javax.swing.JPanel pnlMenumenu;
    private javax.swing.JPanel pnlProjectHeader;
    private javax.swing.JPanel pnlProjectmenu;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTaskHeader;
    private javax.swing.JPanel pnlTaskmenu;
    private javax.swing.JPanel pnlUserHeader;
    private javax.swing.JPanel pnlUsermenu;
    private javax.swing.JPanel pnlWorkingArea;
    // End of variables declaration//GEN-END:variables
}