
package com.ra.View.dashboard;

import java.time.ZonedDateTime; // Để lấy thời gian hiện tại
import java.time.format.DateTimeFormatter; // Để định dạng chuỗi
import java.util.Locale; // Để định dạng theo Locale Nhật Bản
import javax.swing.Timer; // Để cập nhật thời gian mỗi giây
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    
    public MainDashboard() {
        initComponents();
        //GỌI PHƯƠNG THỨC KHỞI ĐỘNG ĐỒNG HỒ Ở ĐÂY
        startClock();
    }
    
    /**
 * Lấy chuỗi ngày giờ hiện tại, định dạng theo Locale Nhật Bản (ja_JP).
 * Định dạng: Năm/Tháng/Ngày (Thứ) Giờ:Phút:Giây
 * Ví dụ: 2025/11/28(金) 15:46:53
 */
private String getCurrentDateTimeJapan() {
    // Lấy thời gian hiện tại
    ZonedDateTime now = ZonedDateTime.now();
    
    // Pattern: yyyy/MM/dd(E) HH:mm:ss
    // E đại diện cho tên thứ ngắn gọn, sẽ được dịch sang tiếng Nhật nhờ Locale.JAPAN
    DateTimeFormatter formatter = DateTimeFormatter
        .ofPattern("yyyy/MM/dd(E) HH:mm:ss")
        .withLocale(Locale.JAPAN); // <--- Sử dụng Locale.JAPAN để dịch tên thứ

    return now.format(formatter);
}
/**
 * Thêm phương thức Khởi động Đồng hồ (Timer)
 */

private void startClock() {
    // Thiết lập Timer để chạy mỗi 1000 mili giây (1 giây)
    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            // Lấy thời gian mới và cập nhật JLabel
            lbDatetime.setText(getCurrentDateTimeJapan());
        }
    });
    timer.start(); // Bắt đầu đồng hồ
}

// ...

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        pnlHeaderSidebar = new javax.swing.JPanel();
        lbHeaderSidebar = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        lbDashboard = new javax.swing.JLabel();
        pnlUserHeader = new javax.swing.JPanel();
        lbUserHeader = new javax.swing.JLabel();
        pnlUsermenu = new javax.swing.JPanel();
        pnlAddUser = new javax.swing.JPanel();
        lbAddUser = new javax.swing.JLabel();
        pnlAllUser = new javax.swing.JPanel();
        lbAllUser = new javax.swing.JLabel();
        pnlDepartmentHeader = new javax.swing.JPanel();
        lbDepartmentHeader = new javax.swing.JLabel();
        pnlDepartmentmenu = new javax.swing.JPanel();
        pnlAdddepartment = new javax.swing.JPanel();
        lbAdddepartment = new javax.swing.JLabel();
        pnlAlldepartment = new javax.swing.JPanel();
        lbAlldepartment = new javax.swing.JLabel();
        pnlProjectHeader = new javax.swing.JPanel();
        lbProjectHeader = new javax.swing.JLabel();
        pnlProjectmenu = new javax.swing.JPanel();
        pnlAddproject = new javax.swing.JPanel();
        lbAddproject = new javax.swing.JLabel();
        pnlAllproject = new javax.swing.JPanel();
        lbAllproject = new javax.swing.JLabel();
        pnlTaskHeader = new javax.swing.JPanel();
        lbTaskHeader = new javax.swing.JLabel();
        pnlTaskmenu = new javax.swing.JPanel();
        pnlAddtask = new javax.swing.JPanel();
        lbAddtask = new javax.swing.JLabel();
        pnlAlltask = new javax.swing.JPanel();
        lbAlltask = new javax.swing.JLabel();
        pnlAttendanceHeader = new javax.swing.JPanel();
        lbAttendanceHeader = new javax.swing.JLabel();
        pnlAttendancemenu = new javax.swing.JPanel();
        pnlAddattendance = new javax.swing.JPanel();
        lbAddattendance = new javax.swing.JLabel();
        pnlViewmonth = new javax.swing.JPanel();
        lbViewmonth = new javax.swing.JLabel();
        pnlViewday = new javax.swing.JPanel();
        lbViewday = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        lbReport = new javax.swing.JLabel();
        pnlMenuHeader = new javax.swing.JPanel();
        lbMenuHeader = new javax.swing.JLabel();
        pnlMenumenu = new javax.swing.JPanel();
        pnlAddmenu = new javax.swing.JPanel();
        lbAddUser2 = new javax.swing.JLabel();
        pnlAllmenu = new javax.swing.JPanel();
        lbAllUser2 = new javax.swing.JLabel();
        pblLogout = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlMainContent = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbDatetime = new javax.swing.JLabel();
        pnlWorkingArea = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ダッシュボード");

        pnlSidebar.setBackground(new java.awt.Color(29, 30, 40));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(250, 300));
        pnlSidebar.setLayout(new javax.swing.BoxLayout(pnlSidebar, javax.swing.BoxLayout.Y_AXIS));

        pnlHeaderSidebar.setBackground(new java.awt.Color(0, 51, 51));
        pnlHeaderSidebar.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlHeaderSidebar.setPreferredSize(new java.awt.Dimension(202, 40));
        pnlHeaderSidebar.setLayout(new java.awt.GridBagLayout());

        lbHeaderSidebar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lbHeaderSidebar.setForeground(new java.awt.Color(255, 255, 255));
        lbHeaderSidebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeaderSidebar.setText("勤怠管理システム");
        lbHeaderSidebar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeaderSidebar.add(lbHeaderSidebar, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlHeaderSidebar);

        pnlDashboard.setBackground(new java.awt.Color(0, 0, 102));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDashboard.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDashboard.setLayout(new java.awt.GridBagLayout());

        lbDashboard.setBackground(new java.awt.Color(0, 0, 102));
        lbDashboard.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbDashboard.setForeground(new java.awt.Color(255, 255, 255));
        lbDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDashboard.setText("ダッシュボード");
        pnlDashboard.add(lbDashboard, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlDashboard);

        pnlUserHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlUserHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlUserHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlUserHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUserHeaderMouseClicked(evt);
            }
        });
        pnlUserHeader.setLayout(new java.awt.GridBagLayout());

        lbUserHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbUserHeader.setText("ユーザー管理");
        pnlUserHeader.add(lbUserHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlUserHeader);

        pnlUsermenu.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlUsermenu.setVisible(false);
        pnlUsermenu.setLayout(new javax.swing.BoxLayout(pnlUsermenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddUser.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddUser.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddUser.setLayout(new java.awt.GridBagLayout());

        lbAddUser.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAddUser.setForeground(new java.awt.Color(255, 255, 255));
        lbAddUser.setText("新ユーザー作成");
        pnlAddUser.add(lbAddUser, new java.awt.GridBagConstraints());

        pnlUsermenu.add(pnlAddUser);

        pnlAllUser.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllUser.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllUser.setLayout(new java.awt.GridBagLayout());

        lbAllUser.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAllUser.setForeground(new java.awt.Color(255, 255, 255));
        lbAllUser.setText("ユーザーリスト");
        pnlAllUser.add(lbAllUser, new java.awt.GridBagConstraints());

        pnlUsermenu.add(pnlAllUser);

        pnlSidebar.add(pnlUsermenu);

        pnlDepartmentHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlDepartmentHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDepartmentHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDepartmentHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDepartmentHeaderMouseClicked(evt);
            }
        });
        pnlDepartmentHeader.setLayout(new java.awt.GridBagLayout());

        lbDepartmentHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbDepartmentHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbDepartmentHeader.setText("部署管理");
        pnlDepartmentHeader.add(lbDepartmentHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlDepartmentHeader);
        pnlDepartmentHeader.getAccessibleContext().setAccessibleName("pnlDepartmentHeader");

        pnlDepartmentmenu.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlDepartmentmenu.setVisible(false);
        pnlDepartmentmenu.setLayout(new javax.swing.BoxLayout(pnlDepartmentmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAdddepartment.setBackground(new java.awt.Color(0, 0, 152));
        pnlAdddepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAdddepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAdddepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAdddepartment.setLayout(new java.awt.GridBagLayout());

        lbAdddepartment.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAdddepartment.setForeground(new java.awt.Color(255, 255, 255));
        lbAdddepartment.setText("新部署作成");
        pnlAdddepartment.add(lbAdddepartment, new java.awt.GridBagConstraints());

        pnlDepartmentmenu.add(pnlAdddepartment);

        pnlAlldepartment.setBackground(new java.awt.Color(0, 0, 152));
        pnlAlldepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAlldepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAlldepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAlldepartment.setLayout(new java.awt.GridBagLayout());

        lbAlldepartment.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAlldepartment.setForeground(new java.awt.Color(255, 255, 255));
        lbAlldepartment.setText("部署リスト");
        pnlAlldepartment.add(lbAlldepartment, new java.awt.GridBagConstraints());

        pnlDepartmentmenu.add(pnlAlldepartment);

        pnlSidebar.add(pnlDepartmentmenu);

        pnlProjectHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlProjectHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlProjectHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProjectHeaderMouseClicked(evt);
            }
        });
        pnlProjectHeader.setLayout(new java.awt.GridBagLayout());

        lbProjectHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbProjectHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbProjectHeader.setText("プロジェクト管理");
        pnlProjectHeader.add(lbProjectHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlProjectHeader);

        pnlProjectmenu.setVisible(false);
        pnlProjectmenu.setLayout(new javax.swing.BoxLayout(pnlProjectmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddproject.setBackground(new java.awt.Color(0, 0, 152));
        pnlAddproject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddproject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddproject.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddproject.setLayout(new java.awt.GridBagLayout());

        lbAddproject.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAddproject.setForeground(new java.awt.Color(255, 255, 255));
        lbAddproject.setText("新プロジェクト作成");
        pnlAddproject.add(lbAddproject, new java.awt.GridBagConstraints());

        pnlProjectmenu.add(pnlAddproject);

        pnlAllproject.setBackground(new java.awt.Color(0, 0, 152));
        pnlAllproject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllproject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllproject.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllproject.setLayout(new java.awt.GridBagLayout());

        lbAllproject.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAllproject.setForeground(new java.awt.Color(255, 255, 255));
        lbAllproject.setText("プロジェクトリスト");
        pnlAllproject.add(lbAllproject, new java.awt.GridBagConstraints());

        pnlProjectmenu.add(pnlAllproject);

        pnlSidebar.add(pnlProjectmenu);

        pnlTaskHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlTaskHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTaskHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTaskHeaderMouseClicked(evt);
            }
        });
        pnlTaskHeader.setLayout(new java.awt.GridBagLayout());

        lbTaskHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbTaskHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbTaskHeader.setText("タスク管理");
        pnlTaskHeader.add(lbTaskHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlTaskHeader);

        pnlTaskmenu.setVisible(false);
        pnlTaskmenu.setLayout(new javax.swing.BoxLayout(pnlTaskmenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddtask.setBackground(new java.awt.Color(0, 0, 152));
        pnlAddtask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddtask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddtask.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddtask.setLayout(new java.awt.GridBagLayout());

        lbAddtask.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAddtask.setForeground(new java.awt.Color(255, 255, 255));
        lbAddtask.setText("新タスク作成");
        pnlAddtask.add(lbAddtask, new java.awt.GridBagConstraints());

        pnlTaskmenu.add(pnlAddtask);

        pnlAlltask.setBackground(new java.awt.Color(0, 0, 152));
        pnlAlltask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAlltask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAlltask.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAlltask.setLayout(new java.awt.GridBagLayout());

        lbAlltask.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAlltask.setForeground(new java.awt.Color(255, 255, 255));
        lbAlltask.setText("タスクリスト");
        pnlAlltask.add(lbAlltask, new java.awt.GridBagConstraints());

        pnlTaskmenu.add(pnlAlltask);

        pnlSidebar.add(pnlTaskmenu);

        pnlAttendanceHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlAttendanceHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlAttendanceHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlAttendanceHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAttendanceHeaderMouseClicked(evt);
            }
        });
        pnlAttendanceHeader.setLayout(new java.awt.GridBagLayout());

        lbAttendanceHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbAttendanceHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbAttendanceHeader.setText("勤怠管理");
        pnlAttendanceHeader.add(lbAttendanceHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlAttendanceHeader);

        pnlAttendancemenu.setDoubleBuffered(false);
        pnlAttendancemenu.setFocusCycleRoot(true);
        pnlAttendancemenu.setMaximumSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setPreferredSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setVisible(false);
        pnlAttendancemenu.setLayout(new javax.swing.BoxLayout(pnlAttendancemenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddattendance.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddattendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddattendance.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddattendance.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddattendance.setLayout(new java.awt.GridBagLayout());

        lbAddattendance.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAddattendance.setForeground(new java.awt.Color(255, 255, 255));
        lbAddattendance.setText("勤務登録");
        pnlAddattendance.add(lbAddattendance, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlAddattendance);

        pnlViewmonth.setBackground(new java.awt.Color(0, 51, 153));
        pnlViewmonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlViewmonth.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlViewmonth.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlViewmonth.setLayout(new java.awt.GridBagLayout());

        lbViewmonth.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbViewmonth.setForeground(new java.awt.Color(255, 255, 255));
        lbViewmonth.setText("月別確認");
        pnlViewmonth.add(lbViewmonth, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlViewmonth);

        pnlViewday.setBackground(new java.awt.Color(0, 51, 153));
        pnlViewday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlViewday.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlViewday.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlViewday.setLayout(new java.awt.GridBagLayout());

        lbViewday.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbViewday.setForeground(new java.awt.Color(255, 255, 255));
        lbViewday.setText("日別詳細確認");
        pnlViewday.add(lbViewday, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlViewday);

        pnlSidebar.add(pnlAttendancemenu);

        pnlReport.setBackground(new java.awt.Color(0, 0, 102));
        pnlReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlReport.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlReport.setLayout(new java.awt.GridBagLayout());

        lbReport.setBackground(new java.awt.Color(0, 0, 102));
        lbReport.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbReport.setForeground(new java.awt.Color(255, 255, 255));
        lbReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbReport.setText("レポート");
        pnlReport.add(lbReport, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlReport);

        pnlMenuHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlMenuHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlMenuHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMenuHeaderMouseClicked(evt);
            }
        });
        pnlMenuHeader.setLayout(new java.awt.GridBagLayout());

        lbMenuHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lbMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        lbMenuHeader.setText("メニュー");
        pnlMenuHeader.add(lbMenuHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlMenuHeader);

        pnlMenumenu.setVisible(false);
        pnlMenumenu.setLayout(new javax.swing.BoxLayout(pnlMenumenu, javax.swing.BoxLayout.Y_AXIS));

        pnlAddmenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddmenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddmenu.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddmenu.setLayout(new java.awt.GridBagLayout());

        lbAddUser2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAddUser2.setForeground(new java.awt.Color(255, 255, 255));
        lbAddUser2.setText("新メニュー作成");
        pnlAddmenu.add(lbAddUser2, new java.awt.GridBagConstraints());

        pnlMenumenu.add(pnlAddmenu);

        pnlAllmenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllmenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllmenu.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllmenu.setLayout(new java.awt.GridBagLayout());

        lbAllUser2.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        lbAllUser2.setForeground(new java.awt.Color(255, 255, 255));
        lbAllUser2.setText("メニューリスト");
        pnlAllmenu.add(lbAllUser2, new java.awt.GridBagConstraints());

        pnlMenumenu.add(pnlAllmenu);

        pnlSidebar.add(pnlMenumenu);

        // CHÈN DÒNG CODE GLUE - Gắn Panel Logout xuống cuối Sidebar
        pnlSidebar.add(javax.swing.Box.createVerticalGlue());

        pblLogout.setBackground(new java.awt.Color(255, 255, 255));
        pblLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pblLogout.setMaximumSize(new java.awt.Dimension(250, 30));
        pblLogout.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        jLabel2.setText("ログアウト");
        pblLogout.add(jLabel2, new java.awt.GridBagConstraints());

        pnlSidebar.add(pblLogout);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlMainContent.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(228, 223, 223));
        pnlHeader.setMaximumSize(new java.awt.Dimension(32767, 42));
        pnlHeader.setPreferredSize(new java.awt.Dimension(100, 42));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lbDatetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDatetime.setText("jLabel3");
        lbDatetime.setMaximumSize(new java.awt.Dimension(200, 60));
        lbDatetime.setPreferredSize(new java.awt.Dimension(250, 42));
        pnlHeader.add(lbDatetime, java.awt.BorderLayout.LINE_END);

        pnlMainContent.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlWorkingArea.setLayout(new java.awt.CardLayout());
        pnlMainContent.add(pnlWorkingArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlUserHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUserHeaderMouseClicked
        pnlUsermenu.setVisible(!pnlUsermenu.isVisible());
        // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlUserHeaderMouseClicked

    private void pnlDepartmentHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDepartmentHeaderMouseClicked
        pnlDepartmentmenu.setVisible(!pnlDepartmentmenu.isVisible());
    // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlDepartmentHeaderMouseClicked

    private void pnlProjectHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProjectHeaderMouseClicked
        pnlProjectmenu.setVisible(!pnlProjectmenu.isVisible());
    // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlProjectHeaderMouseClicked

    private void pnlTaskHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTaskHeaderMouseClicked
            pnlTaskmenu.setVisible(!pnlTaskmenu.isVisible());
    // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlTaskHeaderMouseClicked

    private void pnlAttendanceHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAttendanceHeaderMouseClicked
        pnlAttendancemenu.setVisible(!pnlAttendancemenu.isVisible());
    // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlAttendanceHeaderMouseClicked

    private void pnlMenuHeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMenuHeaderMouseClicked
        pnlMenumenu.setVisible(!pnlMenumenu.isVisible());
    // Yêu cầu Sidebar Panel tính toán lại bố cục do có sự thay đổi kích thước
    pnlSidebar.revalidate(); 
    pnlSidebar.repaint();
    }//GEN-LAST:event_pnlMenuHeaderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbAddUser;
    private javax.swing.JLabel lbAddUser2;
    private javax.swing.JLabel lbAddattendance;
    private javax.swing.JLabel lbAdddepartment;
    private javax.swing.JLabel lbAddproject;
    private javax.swing.JLabel lbAddtask;
    private javax.swing.JLabel lbAllUser;
    private javax.swing.JLabel lbAllUser2;
    private javax.swing.JLabel lbAlldepartment;
    private javax.swing.JLabel lbAllproject;
    private javax.swing.JLabel lbAlltask;
    private javax.swing.JLabel lbAttendanceHeader;
    private javax.swing.JLabel lbDashboard;
    private javax.swing.JLabel lbDatetime;
    private javax.swing.JLabel lbDepartmentHeader;
    private javax.swing.JLabel lbHeaderSidebar;
    private javax.swing.JLabel lbMenuHeader;
    private javax.swing.JLabel lbProjectHeader;
    private javax.swing.JLabel lbReport;
    private javax.swing.JLabel lbTaskHeader;
    private javax.swing.JLabel lbUserHeader;
    private javax.swing.JLabel lbViewday;
    private javax.swing.JLabel lbViewmonth;
    private javax.swing.JPanel pblLogout;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlAddattendance;
    private javax.swing.JPanel pnlAdddepartment;
    private javax.swing.JPanel pnlAddmenu;
    private javax.swing.JPanel pnlAddproject;
    private javax.swing.JPanel pnlAddtask;
    private javax.swing.JPanel pnlAllUser;
    private javax.swing.JPanel pnlAlldepartment;
    private javax.swing.JPanel pnlAllmenu;
    private javax.swing.JPanel pnlAllproject;
    private javax.swing.JPanel pnlAlltask;
    private javax.swing.JPanel pnlAttendanceHeader;
    private javax.swing.JPanel pnlAttendancemenu;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDepartmentHeader;
    private javax.swing.JPanel pnlDepartmentmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderSidebar;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlMenuHeader;
    private javax.swing.JPanel pnlMenumenu;
    private javax.swing.JPanel pnlProjectHeader;
    private javax.swing.JPanel pnlProjectmenu;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTaskHeader;
    private javax.swing.JPanel pnlTaskmenu;
    private javax.swing.JPanel pnlUserHeader;
    private javax.swing.JPanel pnlUsermenu;
    private javax.swing.JPanel pnlViewday;
    private javax.swing.JPanel pnlViewmonth;
    private javax.swing.JPanel pnlWorkingArea;
    // End of variables declaration//GEN-END:variables
}
