package com.ra.View.dashboard;

import com.ra.Model.Entity.Users;
import com.ra.Sercurity.PermissionUtil;

import java.time.ZonedDateTime; // Để lấy thời gian hiện tại
import java.time.format.DateTimeFormatter; // Để định dạng chuỗi
import java.util.Locale; // Để định dạng theo Locale Nhật Bản
import javax.swing.Timer; // Để cập nhật thời gian mỗi giây
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Box;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;

public class MainDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainDashboard.class.getName());

    private Users currentUser;

    public MainDashboard(Users user) {
        this.currentUser = user;
        initComponents();
        startClock();
        applyRoleAccess();   // GỌI PHÂN QUYỀN Ở ĐÂY
    }
    private void applyRoleAccess() {
        int roleId = currentUser.getRole().getId();

        System.out.println("ROLE APPLY => " + roleId);
        //tạm thời

        switch (roleId) {
            case 3: // ADMIN
                // Admin xem tất cả
                break;

            case 2: // MANAGER

                pnlMenuHeader.setVisible(false);
                pnlProjectHeader.setVisible(false);
                pnlDepartmentHeader.setVisible(false);
                pnlTaskHeader.setVisible(false);
                break;

            case 1: // EMPLOYEE
                pnlUserHeader.setVisible(false);
                pnlDepartmentHeader.setVisible(false);
                pnlProjectHeader.setVisible(false);
                pnlMenuHeader.setVisible(false);
                pnlTaskHeader.setVisible(false);
                break;
        }
    }




    private String getCurrentDateTimeJapan() {
        ZonedDateTime now = ZonedDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter
                .ofPattern("yyyy/MM/dd(E) HH:mm:ss")
                .withLocale(Locale.JAPAN);
        return now.format(formatter);
    }


    private void startClock() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                lbDatetime.setText(getCurrentDateTimeJapan());
            }
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlSidebar = new javax.swing.JPanel();
        pnlHeaderSidebar = new javax.swing.JPanel();
        lbHeaderSidebar = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        pnlUserHeader = new javax.swing.JPanel();
        btnUserHeader = new javax.swing.JButton();
        pnlUsermenu = new javax.swing.JPanel();
        pnlAddUser = new javax.swing.JPanel();
        btnAddUser = new javax.swing.JButton();
        pnlAllUser = new javax.swing.JPanel();
        btnAllUser = new javax.swing.JButton();
        pnlDepartmentHeader = new javax.swing.JPanel();
        btnDepartmentHeader = new javax.swing.JButton();
        pnlDepartmentmenu = new javax.swing.JPanel();
        pnlAdddepartment = new javax.swing.JPanel();
        btnAdddepartment = new javax.swing.JButton();
        pnlAlldepartment = new javax.swing.JPanel();
        btnAlldepartment = new javax.swing.JButton();
        pnlProjectHeader = new javax.swing.JPanel();
        btnProjectHeader = new javax.swing.JButton();
        pnlProjectmenu = new javax.swing.JPanel();
        pnlAddproject = new javax.swing.JPanel();
        btnAddproject = new javax.swing.JButton();
        pnlAllproject = new javax.swing.JPanel();
        btnAllproject = new javax.swing.JButton();
        pnlTaskHeader = new javax.swing.JPanel();
        btnTaskHeader = new javax.swing.JButton();
        pnlTaskmenu = new javax.swing.JPanel();
        pnlAddtask = new javax.swing.JPanel();
        btnAddtask = new javax.swing.JButton();
        pnlAlltask = new javax.swing.JPanel();
        btnAlltask = new javax.swing.JButton();
        pnlAttendanceHeader = new javax.swing.JPanel();
        btnAttendanceHeader = new javax.swing.JButton();
        pnlAttendancemenu = new javax.swing.JPanel();
        pnlAddattendance = new javax.swing.JPanel();
        btnAddattendance = new javax.swing.JButton();
        pnlViewmonth = new javax.swing.JPanel();
        btnViewmonth = new javax.swing.JButton();
        pnlViewday = new javax.swing.JPanel();
        btnViewday = new javax.swing.JButton();
        pnlReport = new javax.swing.JPanel();
        btnReport = new javax.swing.JButton();
        pnlMenuHeader = new javax.swing.JPanel();
        btnMenuHeader = new javax.swing.JButton();
        pnlMenumenu = new javax.swing.JPanel();
        pnlAddmenu = new javax.swing.JPanel();
        btnAddmenu = new javax.swing.JButton();
        pnlAllmenu = new javax.swing.JPanel();
        btnAllmenu = new javax.swing.JButton();
        pblLogout = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        pnlMainContent = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        lbDatetime = new javax.swing.JLabel();
        pnlWorkingArea = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ダッシュボード");

        pnlSidebar.setBackground(new java.awt.Color(29, 30, 40));
        pnlSidebar.setPreferredSize(new java.awt.Dimension(250, 300));
        pnlSidebar.setLayout(new javax.swing.BoxLayout(pnlSidebar, javax.swing.BoxLayout.Y_AXIS));

        pnlHeaderSidebar.setBackground(new java.awt.Color(0, 51, 51));
        pnlHeaderSidebar.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlHeaderSidebar.setPreferredSize(new java.awt.Dimension(202, 40));
        pnlHeaderSidebar.setLayout(new java.awt.GridBagLayout());

        lbHeaderSidebar.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        lbHeaderSidebar.setForeground(new java.awt.Color(255, 255, 255));
        lbHeaderSidebar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHeaderSidebar.setText("勤怠管理システム");
        lbHeaderSidebar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeaderSidebar.add(lbHeaderSidebar, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlHeaderSidebar);

        // DASHBOARD (JPanel giữ nguyên)
        pnlDashboard.setBackground(new java.awt.Color(0, 0, 102));
        pnlDashboard.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDashboard.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDashboard.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbDashboard bằng btnDashboard
        btnDashboard.setBackground(new java.awt.Color(0, 0, 102));
        btnDashboard.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashboard.setText("ダッシュボード");
        btnDashboard.setBorderPainted(false); // Loại bỏ viền của Button
        btnDashboard.setFocusPainted(false); // Loại bỏ focus ring
        btnDashboard.setContentAreaFilled(false); // Đảm bảo Button trong suốt trên Panel
        pnlDashboard.add(btnDashboard, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlDashboard);

        // USER HEADER (JPanel giữ nguyên)
        pnlUserHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlUserHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlUserHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlUserHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbUserHeader bằng btnUserHeader
        btnUserHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnUserHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnUserHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnUserHeader.setText("ユーザー管理");
        btnUserHeader.setBorderPainted(false);
        btnUserHeader.setFocusPainted(false);
        btnUserHeader.setContentAreaFilled(false);
        btnUserHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserHeaderActionPerformed(evt);
            }
        });
        pnlUserHeader.add(btnUserHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlUserHeader);

        pnlUsermenu.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlUsermenu.setVisible(false);
        pnlUsermenu.setLayout(new javax.swing.BoxLayout(pnlUsermenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD USER (JPanel giữ nguyên)
        pnlAddUser.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddUser.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddUser.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAddUser bằng btnAddUser
        btnAddUser.setBackground(new java.awt.Color(0, 51, 153));
        btnAddUser.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAddUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAddUser.setText("新ユーザー作成");
        btnAddUser.setBorderPainted(false);
        btnAddUser.setFocusPainted(false);
        btnAddUser.setContentAreaFilled(false);
        pnlAddUser.add(btnAddUser, new java.awt.GridBagConstraints());

        pnlUsermenu.add(pnlAddUser);

        // ALL USER (JPanel giữ nguyên)
        pnlAllUser.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllUser.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllUser.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllUser.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAllUser bằng btnAllUser
        btnAllUser.setBackground(new java.awt.Color(0, 51, 153));
        btnAllUser.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAllUser.setForeground(new java.awt.Color(255, 255, 255));
        btnAllUser.setText("ユーザーリスト");
        btnAllUser.setBorderPainted(false);
        btnAllUser.setFocusPainted(false);
        btnAllUser.setContentAreaFilled(false);
        pnlAllUser.add(btnAllUser, new java.awt.GridBagConstraints());

        pnlUsermenu.add(pnlAllUser);

        pnlSidebar.add(pnlUsermenu);

        // DEPARTMENT HEADER (JPanel giữ nguyên)
        pnlDepartmentHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlDepartmentHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlDepartmentHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlDepartmentHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbDepartmentHeader bằng btnDepartmentHeader
        btnDepartmentHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnDepartmentHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnDepartmentHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnDepartmentHeader.setText("部署管理");
        btnDepartmentHeader.setBorderPainted(false);
        btnDepartmentHeader.setFocusPainted(false);
        btnDepartmentHeader.setContentAreaFilled(false);
        btnDepartmentHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentHeaderActionPerformed(evt);
            }
        });
        pnlDepartmentHeader.add(btnDepartmentHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlDepartmentHeader);

        pnlDepartmentmenu.setMaximumSize(new java.awt.Dimension(250, 60));
        pnlDepartmentmenu.setVisible(false);
        pnlDepartmentmenu.setLayout(new javax.swing.BoxLayout(pnlDepartmentmenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD DEPARTMENT (JPanel giữ nguyên)
        pnlAdddepartment.setBackground(new java.awt.Color(0, 0, 152));
        pnlAdddepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAdddepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAdddepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAdddepartment.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAdddepartment bằng btnAdddepartment
        btnAdddepartment.setBackground(new java.awt.Color(0, 0, 152));
        btnAdddepartment.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAdddepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAdddepartment.setText("新部署作成");
        btnAdddepartment.setBorderPainted(false);
        btnAdddepartment.setFocusPainted(false);
        btnAdddepartment.setContentAreaFilled(false);
        pnlAdddepartment.add(btnAdddepartment, new java.awt.GridBagConstraints());

        pnlDepartmentmenu.add(pnlAdddepartment);

        // ALL DEPARTMENT (JPanel giữ nguyên)
        pnlAlldepartment.setBackground(new java.awt.Color(0, 0, 152));
        pnlAlldepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAlldepartment.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAlldepartment.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAlldepartment.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAlldepartment bằng btnAlldepartment
        btnAlldepartment.setBackground(new java.awt.Color(0, 0, 152));
        btnAlldepartment.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAlldepartment.setForeground(new java.awt.Color(255, 255, 255));
        btnAlldepartment.setText("部署リスト");
        btnAlldepartment.setBorderPainted(false);
        btnAlldepartment.setFocusPainted(false);
        btnAlldepartment.setContentAreaFilled(false);
        pnlAlldepartment.add(btnAlldepartment, new java.awt.GridBagConstraints());

        pnlDepartmentmenu.add(pnlAlldepartment);

        pnlSidebar.add(pnlDepartmentmenu);

        // PROJECT HEADER (JPanel giữ nguyên)
        pnlProjectHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlProjectHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlProjectHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlProjectHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbProjectHeader bằng btnProjectHeader
        btnProjectHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnProjectHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnProjectHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnProjectHeader.setText("プロジェクト管理");
        btnProjectHeader.setBorderPainted(false);
        btnProjectHeader.setFocusPainted(false);
        btnProjectHeader.setContentAreaFilled(false);
        btnProjectHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjectHeaderActionPerformed(evt);
            }
        });
        pnlProjectHeader.add(btnProjectHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlProjectHeader);

        pnlProjectmenu.setVisible(false);
        pnlProjectmenu.setLayout(new javax.swing.BoxLayout(pnlProjectmenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD PROJECT (JPanel giữ nguyên)
        pnlAddproject.setBackground(new java.awt.Color(0, 0, 152));
        pnlAddproject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddproject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddproject.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddproject.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAddproject bằng btnAddproject
        btnAddproject.setBackground(new java.awt.Color(0, 0, 152));
        btnAddproject.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAddproject.setForeground(new java.awt.Color(255, 255, 255));
        btnAddproject.setText("新プロジェクト作成");
        btnAddproject.setBorderPainted(false);
        btnAddproject.setFocusPainted(false);
        btnAddproject.setContentAreaFilled(false);
        pnlAddproject.add(btnAddproject, new java.awt.GridBagConstraints());

        pnlProjectmenu.add(pnlAddproject);

        // ALL PROJECT (JPanel giữ nguyên)
        pnlAllproject.setBackground(new java.awt.Color(0, 0, 152));
        pnlAllproject.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllproject.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllproject.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllproject.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAllproject bằng btnAllproject
        btnAllproject.setBackground(new java.awt.Color(0, 0, 152));
        btnAllproject.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAllproject.setForeground(new java.awt.Color(255, 255, 255));
        btnAllproject.setText("プロジェクトリスト");
        btnAllproject.setBorderPainted(false);
        btnAllproject.setFocusPainted(false);
        btnAllproject.setContentAreaFilled(false);
        pnlAllproject.add(btnAllproject, new java.awt.GridBagConstraints());

        pnlProjectmenu.add(pnlAllproject);

        pnlSidebar.add(pnlProjectmenu);

        // TASK HEADER (JPanel giữ nguyên)
        pnlTaskHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlTaskHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTaskHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlTaskHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbTaskHeader bằng btnTaskHeader
        btnTaskHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnTaskHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnTaskHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnTaskHeader.setText("タスク管理");
        btnTaskHeader.setBorderPainted(false);
        btnTaskHeader.setFocusPainted(false);
        btnTaskHeader.setContentAreaFilled(false);
        btnTaskHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskHeaderActionPerformed(evt);
            }
        });
        pnlTaskHeader.add(btnTaskHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlTaskHeader);

        pnlTaskmenu.setVisible(false);
        pnlTaskmenu.setLayout(new javax.swing.BoxLayout(pnlTaskmenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD TASK (JPanel giữ nguyên)
        pnlAddtask.setBackground(new java.awt.Color(0, 0, 152));
        pnlAddtask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddtask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddtask.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddtask.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAddtask bằng btnAddtask
        btnAddtask.setBackground(new java.awt.Color(0, 0, 152));
        btnAddtask.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAddtask.setForeground(new java.awt.Color(255, 255, 255));
        btnAddtask.setText("新タスク作成");
        btnAddtask.setBorderPainted(false);
        btnAddtask.setFocusPainted(false);
        btnAddtask.setContentAreaFilled(false);
        pnlAddtask.add(btnAddtask, new java.awt.GridBagConstraints());

        pnlTaskmenu.add(pnlAddtask);

        // ALL TASK (JPanel giữ nguyên)
        pnlAlltask.setBackground(new java.awt.Color(0, 0, 152));
        pnlAlltask.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAlltask.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAlltask.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAlltask.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAlltask bằng btnAlltask
        btnAlltask.setBackground(new java.awt.Color(0, 0, 152));
        btnAlltask.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAlltask.setForeground(new java.awt.Color(255, 255, 255));
        btnAlltask.setText("タスクリスト");
        btnAlltask.setBorderPainted(false);
        btnAlltask.setFocusPainted(false);
        btnAlltask.setContentAreaFilled(false);
        pnlAlltask.add(btnAlltask, new java.awt.GridBagConstraints());

        pnlTaskmenu.add(pnlAlltask);

        pnlSidebar.add(pnlTaskmenu);

        // ATTENDANCE HEADER (JPanel giữ nguyên)
        pnlAttendanceHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlAttendanceHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlAttendanceHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlAttendanceHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAttendanceHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAttendanceHeader bằng btnAttendanceHeader
        btnAttendanceHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnAttendanceHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnAttendanceHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnAttendanceHeader.setText("勤怠管理");
        btnAttendanceHeader.setBorderPainted(false);
        btnAttendanceHeader.setFocusPainted(false);
        btnAttendanceHeader.setContentAreaFilled(false);
        btnAttendanceHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendanceHeaderActionPerformed(evt);
            }
        });
        pnlAttendanceHeader.add(btnAttendanceHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlAttendanceHeader);

        pnlAttendancemenu.setDoubleBuffered(false);
        pnlAttendancemenu.setFocusCycleRoot(true);
        pnlAttendancemenu.setMaximumSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setPreferredSize(new java.awt.Dimension(250, 90));
        pnlAttendancemenu.setVisible(false);
        pnlAttendancemenu.setLayout(new javax.swing.BoxLayout(pnlAttendancemenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD ATTENDANCE (JPanel giữ nguyên)
        pnlAddattendance.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddattendance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddattendance.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddattendance.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddattendance.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAddattendance bằng btnAddattendance
        btnAddattendance.setBackground(new java.awt.Color(0, 51, 153));
        btnAddattendance.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAddattendance.setForeground(new java.awt.Color(255, 255, 255));
        btnAddattendance.setText("勤務登録");
        btnAddattendance.setBorderPainted(false);
        btnAddattendance.setFocusPainted(false);
        btnAddattendance.setContentAreaFilled(false);
        pnlAddattendance.add(btnAddattendance, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlAddattendance);

        // VIEW MONTH (JPanel giữ nguyên)
        pnlViewmonth.setBackground(new java.awt.Color(0, 51, 153));
        pnlViewmonth.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlViewmonth.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlViewmonth.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlViewmonth.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbViewmonth bằng btnViewmonth
        btnViewmonth.setBackground(new java.awt.Color(0, 51, 153));
        btnViewmonth.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnViewmonth.setForeground(new java.awt.Color(255, 255, 255));
        btnViewmonth.setText("月別確認");
        btnViewmonth.setBorderPainted(false);
        btnViewmonth.setFocusPainted(false);
        btnViewmonth.setContentAreaFilled(false);
        pnlViewmonth.add(btnViewmonth, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlViewmonth);

        // VIEW DAY (JPanel giữ nguyên)
        pnlViewday.setBackground(new java.awt.Color(0, 51, 153));
        pnlViewday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlViewday.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlViewday.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlViewday.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbViewday bằng btnViewday
        btnViewday.setBackground(new java.awt.Color(0, 51, 153));
        btnViewday.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnViewday.setForeground(new java.awt.Color(255, 255, 255));
        btnViewday.setText("日別詳細確認");
        btnViewday.setBorderPainted(false);
        btnViewday.setFocusPainted(false);
        btnViewday.setContentAreaFilled(false);
        pnlViewday.add(btnViewday, new java.awt.GridBagConstraints());

        pnlAttendancemenu.add(pnlViewday);

        pnlSidebar.add(pnlAttendancemenu);

        // REPORT (JPanel giữ nguyên)
        pnlReport.setBackground(new java.awt.Color(0, 0, 102));
        pnlReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlReport.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlReport.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbReport bằng btnReport
        btnReport.setBackground(new java.awt.Color(0, 0, 102));
        btnReport.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnReport.setForeground(new java.awt.Color(255, 255, 255));
        btnReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReport.setText("レポート");
        btnReport.setBorderPainted(false);
        btnReport.setFocusPainted(false);
        btnReport.setContentAreaFilled(false);
        pnlReport.add(btnReport, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlReport);

        // MENU HEADER (JPanel giữ nguyên)
        pnlMenuHeader.setBackground(new java.awt.Color(0, 0, 102));
        pnlMenuHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        pnlMenuHeader.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlMenuHeader.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbMenuHeader bằng btnMenuHeader
        btnMenuHeader.setBackground(new java.awt.Color(0, 0, 102));
        btnMenuHeader.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuHeader.setText("メニュー");
        btnMenuHeader.setBorderPainted(false);
        btnMenuHeader.setFocusPainted(false);
        btnMenuHeader.setContentAreaFilled(false);
        btnMenuHeader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuHeaderActionPerformed(evt);
            }
        });
        pnlMenuHeader.add(btnMenuHeader, new java.awt.GridBagConstraints());

        pnlSidebar.add(pnlMenuHeader);

        pnlMenumenu.setVisible(false);
        pnlMenumenu.setLayout(new javax.swing.BoxLayout(pnlMenumenu, javax.swing.BoxLayout.Y_AXIS));

        // ADD MENU (JPanel giữ nguyên)
        pnlAddmenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAddmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddmenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAddmenu.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAddmenu.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAddUser2 bằng btnAddmenu
        btnAddmenu.setBackground(new java.awt.Color(0, 51, 153));
        btnAddmenu.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAddmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAddmenu.setText("新メニュー作成");
        btnAddmenu.setBorderPainted(false);
        btnAddmenu.setFocusPainted(false);
        btnAddmenu.setContentAreaFilled(false);
        pnlAddmenu.add(btnAddmenu, new java.awt.GridBagConstraints());

        pnlMenumenu.add(pnlAddmenu);

        // ALL MENU (JPanel giữ nguyên)
        pnlAllmenu.setBackground(new java.awt.Color(0, 51, 153));
        pnlAllmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAllmenu.setMaximumSize(new java.awt.Dimension(250, 30));
        pnlAllmenu.setPreferredSize(new java.awt.Dimension(250, 30));
        pnlAllmenu.setLayout(new java.awt.GridBagLayout());

        // Thay thế lbAllUser2 bằng btnAllmenu
        btnAllmenu.setBackground(new java.awt.Color(0, 51, 153));
        btnAllmenu.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        btnAllmenu.setForeground(new java.awt.Color(255, 255, 255));
        btnAllmenu.setText("メニューリスト");
        btnAllmenu.setBorderPainted(false);
        btnAllmenu.setFocusPainted(false);
        btnAllmenu.setContentAreaFilled(false);
        pnlAllmenu.add(btnAllmenu, new java.awt.GridBagConstraints());

        pnlMenumenu.add(pnlAllmenu);

        pnlSidebar.add(pnlMenumenu);
        pblLogout.setBackground(new java.awt.Color(255, 255, 255));
        pblLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pblLogout.setMaximumSize(new java.awt.Dimension(250, 30));
        pblLogout.setLayout(new java.awt.GridBagLayout());

        // Thay thế jLabel2 bằng btnLogOut
        btnLogOut.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        btnLogOut.setText("ログアウト");
        btnLogOut.setBorderPainted(false);
        btnLogOut.setFocusPainted(false);
        btnLogOut.setContentAreaFilled(false);
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pblLogout.add(btnLogOut, new java.awt.GridBagConstraints());

        pnlSidebar.add(pblLogout);

        getContentPane().add(pnlSidebar, java.awt.BorderLayout.LINE_START);

        pnlMainContent.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(228, 223, 223));
        pnlHeader.setMaximumSize(new java.awt.Dimension(32767, 42));
        pnlHeader.setPreferredSize(new java.awt.Dimension(100, 42));
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lbDatetime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDatetime.setText("jLabel3");
        lbDatetime.setMaximumSize(new java.awt.Dimension(200, 60));
        lbDatetime.setPreferredSize(new java.awt.Dimension(250, 42));
        pnlHeader.add(lbDatetime, java.awt.BorderLayout.LINE_END);

        pnlMainContent.add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlWorkingArea.setLayout(new java.awt.CardLayout());


        pnlMainContent.add(pnlWorkingArea, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlMainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ********** PHƯƠNG THỨC XỬ LÝ SỰ KIỆN ActionPerformed **********

    private void btnUserHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlUsermenu.setVisible(!pnlUsermenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnDepartmentHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlDepartmentmenu.setVisible(!pnlDepartmentmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnProjectHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlProjectmenu.setVisible(!pnlProjectmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnTaskHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlTaskmenu.setVisible(!pnlTaskmenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnAttendanceHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlAttendancemenu.setVisible(!pnlAttendancemenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnMenuHeaderActionPerformed(java.awt.event.ActionEvent evt) {
        pnlMenumenu.setVisible(!pnlMenumenu.isVisible());
        pnlSidebar.revalidate();
        pnlSidebar.repaint();
    }

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {
        // Logic xử lý Logout
        System.out.println("Thực hiện Logout...");
    }

    private void jLocaleChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocaleChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLocaleChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        *//* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        *//* Create and display the form *//*
        java.awt.EventQueue.invokeLater(() -> new MainDashboard(user).setVisible(true);

    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnAddattendance;
    private javax.swing.JButton btnAdddepartment;
    private javax.swing.JButton btnAddmenu;
    private javax.swing.JButton btnAddproject;
    private javax.swing.JButton btnAddtask;
    private javax.swing.JButton btnAllUser;
    private javax.swing.JButton btnAllmenu;
    private javax.swing.JButton btnAlldepartment;
    private javax.swing.JButton btnAllproject;
    private javax.swing.JButton btnAlltask;
    private javax.swing.JButton btnAttendanceHeader;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDepartmentHeader;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenuHeader;
    private javax.swing.JButton btnProjectHeader;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnTaskHeader;
    private javax.swing.JButton btnUserHeader;
    private javax.swing.JButton btnViewday;
    private javax.swing.JButton btnViewmonth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbHeaderSidebar;
    private javax.swing.JLabel lbDatetime;
    private javax.swing.JPanel pblLogout;
    private javax.swing.JPanel pnlAddUser;
    private javax.swing.JPanel pnlAddattendance;
    private javax.swing.JPanel pnlAdddepartment;
    private javax.swing.JPanel pnlAddmenu;
    private javax.swing.JPanel pnlAddproject;
    private javax.swing.JPanel pnlAddtask;
    private javax.swing.JPanel pnlAllUser;
    private javax.swing.JPanel pnlAlldepartment;
    private javax.swing.JPanel pnlAllmenu;
    private javax.swing.JPanel pnlAllproject;
    private javax.swing.JPanel pnlAlltask;
    private javax.swing.JPanel pnlAttendanceHeader;
    private javax.swing.JPanel pnlAttendancemenu;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlDepartmentHeader;
    private javax.swing.JPanel pnlDepartmentmenu;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeaderSidebar;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlMenuHeader;
    private javax.swing.JPanel pnlMenumenu;
    private javax.swing.JPanel pnlProjectHeader;
    private javax.swing.JPanel pnlProjectmenu;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JPanel pnlTaskHeader;
    private javax.swing.JPanel pnlTaskmenu;
    private javax.swing.JPanel pnlUserHeader;
    private javax.swing.JPanel pnlUsermenu;
    private javax.swing.JPanel pnlViewday;
    private javax.swing.JPanel pnlViewmonth;
    private javax.swing.JPanel pnlWorkingArea;
    // End of variables declaration//GEN-END:variables
}