/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ra.View.attendance;

import com.ra.Common.Constant;
import com.ra.Controller.*;
import com.ra.DAO.Holiday.HolidayDAO;
import com.ra.DAO.Project.ProjectDAO;
import com.ra.DAO.Task.TaskDAO;
import com.ra.Model.Entity.*;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;

/**
 *
 * @author admin
 */
// THAY ĐỔI: Chuyển từ extends JFrame sang extends JPanel
public class AddAttendance extends JPanel {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddAttendance.class.getName());

    /**
     * Creates new form AddAttendance
     */
    private Users loggedInUser;



    private Constant constant = new Constant();
    private AttendanceController attendanceController = new AttendanceController();
    private RecordController recordController ;
    private TaskController taskController ;
    private ProjectController projectController ;

    public AddAttendance(Users user) {
        initComponents();
        this.loggedInUser = user;
        this.recordController = new RecordController();
        loadUserInfo();
        loadProjects();
        loadTasks();
        initStatusComboBox();

    }
    private List<Attendance> getCurrentAttendance(int userId, LocalDate date) {
        return attendanceController.findByUserAndDate(userId, date);
    }
    private void initStatusComboBox() {
        cbStatus.removeAllItems();
        cbStatus.addItem("未確認");   // Status 0
        cbStatus.addItem("確認済み"); // Status 1
        cbStatus.addItem("拒否済み"); // Status 2
    }
    private void loadWorkRecordTable(int attendanceId) {

        List<WorkRecord> list = recordController.findByAttendanceId(attendanceId);

        DefaultTableModel model = (DefaultTableModel) tblRecord.getModel();
        model.setRowCount(0); // clear table

        int maxRecords = Math.min(list.size(), 20);

        for (int i = 0; i < maxRecords; i++) {

            WorkRecord wr = list.get(i);

            // Convert status
            String statusText;
            if (wr.getStatus() == 0) {
                statusText = "未確認";   // chưa xác nhận
            } else if (wr.getStatus() == 1) {
                statusText = "確認済み"; // đã xác nhận
            } else {
                statusText = "拒否済み"; // từ chối
            }

            Object[] row = new Object[]{
                    i + 1,
                    wr.getProject() != null ? wr.getProject().getName() : "",
                    wr.getTask() != null ? wr.getTask().getName() : "",
                    wr.getStartTime(),
                    wr.getEndTime(),
                    wr.getWorkMinutes(),
                    wr.getBreakWork(),
                    statusText,
                    wr.getRemarks()
            };

            model.addRow(row);
        }


        centerTableColumns(tblRecord);
    }
    private void centerTableColumns(JTable table) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLayeredPane1 = new JLayeredPane();
        jComboBox3 = new JComboBox<>();
        jLabel12 = new JLabel();
        buttonGroup1 = new ButtonGroup();
        buttonGroup2 = new ButtonGroup();
        jRadioButton1 = new JRadioButton();
        pnlAddAttendance = new JPanel();
        jSeparator1 = new JSeparator();
        jSeparator2 = new JSeparator();
        jScrollPane1 = new JScrollPane();
        tblRecord = new JTable();
        btnWorkinformation = new JButton();
        btnCreatecontent = new JButton();
        lbEmployee = new JLabel();
        txtEmployeeName = new JTextField();
        lbCalendar = new JLabel();
        lbEarlieststarttime = new JLabel();
        lbLatestendtime = new JLabel();
        txtValidate = new JLabel();
        lbStarttime = new JLabel();
        lbEndtime = new JLabel();
        lbBreaktimetotask = new JLabel();
        lbProject = new JLabel();
        cbProject = new JComboBox<>();
        cbTask = new JComboBox<>();
        lbTaskName = new JLabel();
        btnAddAttend = new JButton();
        jToggleButton1 = new JToggleButton();
        lbWorktime = new JLabel();
        lbOvertime = new JLabel();
        lbBreaktime = new JLabel();
        btnUpdateRecord = new JButton();
        btnDelete = new JButton();
        btnAddRecord = new JButton();
        rbHoliday = new JRadioButton();
        csDate = new com.toedter.calendar.JDateChooser();
        fmStart = fmCheckIn = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmEnd = fmCheckIn = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmTotal = fmTotal = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmOverTime = fmOverTime = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmBreakTime = fmBreakTime = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmCheckIn = fmCheckOut = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        fmCheckOut = fmCheckOut = new JFormattedTextField(
                new javax.swing.text.DateFormatter(
                        new SimpleDateFormat("HH:mm")
                )
        );
        ;
        jLabel1 = new JLabel();
        txtRemark = new JTextField();
        lbBreaktimetotask1 = new JLabel();
        cbStatus = new JComboBox<>();
        txtBreak = new JTextField();

        popupMenu1.setLabel("popupMenu1");

        GroupLayout jLayeredPane1Layout = new GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox3.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("jLabel11");

        jRadioButton1.setText("jRadioButton1");

        // LOẠI BỎ: setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblRecord.setModel(new DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "No", "プロジェクト名", "タスク名", "開始", "終了", "勤務時間", "休憩時間", "Status", "Remark"
                }
        ) {
            Class[] types = new Class [] {
                    Integer.class, Object.class, Object.class, String.class, String.class, String.class, String.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblRecord.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblRecord);
        tblRecord.getColumnModel().getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        btnWorkinformation.setBackground(new java.awt.Color(255, 255, 204));
        btnWorkinformation.setText("勤怠情報");
        btnWorkinformation.addActionListener(this::btnWorkinformationActionPerformed);

        btnCreatecontent.setBackground(new java.awt.Color(255, 255, 204));
        btnCreatecontent.setText("作成内容");
        btnCreatecontent.setToolTipText("");
        btnCreatecontent.addActionListener(this::btnCreatecontentActionPerformed);

        lbEmployee.setText("社員名");

        txtEmployeeName.setText("ログイン社員名");
        txtEmployeeName.addActionListener(this::txtEmployeeNameActionPerformed);

        lbCalendar.setText("日付");

        lbEarlieststarttime.setText("最始");

        lbLatestendtime.setText("最終");

        txtValidate.setFont(new java.awt.Font("Yu Gothic", 0, 8)); // NOI18N
        txtValidate.setForeground(new java.awt.Color(255, 0, 51));
        txtValidate.setText("※未来の値入力不可");

        lbStarttime.setText("開始");

        lbEndtime.setText("終了");

        lbBreaktimetotask.setText("休憩");

        lbProject.setText("プロジェクト名");

        cbTask.addActionListener(this::cbTaskActionPerformed);

        lbTaskName.setText("タスク名");

        btnAddAttend.setBackground(new java.awt.Color(204, 255, 204));
        btnAddAttend.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddAttend.setText("追加");
        btnAddAttend.addActionListener(this::btnAddAttendActionPerformed);

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setText("合計");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        lbWorktime.setText("勤務時間");

        lbOvertime.setText("残業時間");

        lbBreaktime.setText("休憩時間");

        btnUpdateRecord.setBackground(new java.awt.Color(204, 255, 255));
        btnUpdateRecord.setText("編集");

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setText("削除");

        btnAddRecord.setBackground(new java.awt.Color(153, 255, 153));
        btnAddRecord.setText("追加");
        btnAddRecord.addActionListener(this::btnAddRecordActionPerformed);

        rbHoliday.setText("休日");

        fmStart.addActionListener(this::fmStartActionPerformed);

        fmEnd.addActionListener(this::fmEndActionPerformed);

        fmTotal.addActionListener(this::fmTotalActionPerformed);

        fmOverTime.addActionListener(this::fmOverTimeActionPerformed);

        fmBreakTime.addActionListener(this::fmBreakTimeActionPerformed);

        fmCheckIn.addActionListener(this::fmCheckInActionPerformed);

        fmCheckOut.addActionListener(this::fmCheckOutActionPerformed);

        jLabel1.setText("述べる");

        lbBreaktimetotask1.setText("状態");

        GroupLayout pnlAddAttendanceLayout = new GroupLayout(pnlAddAttendance);
        pnlAddAttendance.setLayout(pnlAddAttendanceLayout);
        pnlAddAttendanceLayout.setHorizontalGroup(
                pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addGroup(GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnCreatecontent, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jToggleButton1, GroupLayout.PREFERRED_SIZE, 584, GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(btnAddRecord)
                                                                .addGap(29, 29, 29)))
                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 514, GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                .addComponent(btnUpdateRecord)
                                                                .addGap(33, 33, 33)
                                                                .addComponent(btnDelete))))
                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(lbStarttime, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fmStart, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
                                                .addGap(78, 78, 78)
                                                .addComponent(lbEndtime, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(fmEnd, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbBreaktimetotask, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtBreak, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                                .addGap(35, 35, 35)
                                                .addComponent(lbBreaktimetotask1, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbStatus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                .addGap(324, 324, 324))
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                        .addGap(33, 33, 33)
                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                        .addComponent(lbEmployee, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtEmployeeName, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(37, 37, 37)
                                                                        .addComponent(lbEarlieststarttime, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                        .addComponent(lbCalendar, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(38, 38, 38)
                                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txtValidate, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(csDate, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                        .addGap(28, 28, 28)
                                                                        .addComponent(rbHoliday, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addGroup(GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(fmCheckIn, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(68, 68, 68)
                                                                                .addComponent(lbLatestendtime, GroupLayout.PREFERRED_SIZE, 37, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(fmCheckOut, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                                .addGap(205, 205, 205)
                                                                                .addComponent(btnAddAttend, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addComponent(btnWorkinformation, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                                        .addGap(35, 35, 35)
                                                                        .addComponent(lbWorktime)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(fmTotal, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(59, 59, 59)
                                                                        .addComponent(lbOvertime)
                                                                        .addGap(28, 28, 28)
                                                                        .addComponent(fmOverTime, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(44, 44, 44)
                                                                        .addComponent(lbBreaktime)
                                                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(fmBreakTime, GroupLayout.PREFERRED_SIZE, 67, GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 760, GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addComponent(lbProject)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbProject, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(lbTaskName, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbTask, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel1)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtRemark, GroupLayout.PREFERRED_SIZE, 119, GroupLayout.PREFERRED_SIZE)
                                                .addGap(427, 427, 427)))
                                .addContainerGap())
        );
        pnlAddAttendanceLayout.setVerticalGroup(
                pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                .addComponent(btnWorkinformation)
                                .addGap(4, 4, 4)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                                .addComponent(lbEmployee)
                                                                .addComponent(txtEmployeeName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                                .addComponent(lbEarlieststarttime)
                                                                .addComponent(lbLatestendtime)
                                                                .addComponent(fmCheckIn, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(fmCheckOut, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(csDate, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbCalendar)))
                                        .addComponent(rbHoliday))
                                .addGap(3, 3, 3)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAddAttend, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(txtValidate)))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCreatecontent)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbStarttime)
                                        .addComponent(lbEndtime)
                                        .addComponent(lbBreaktimetotask)
                                        .addComponent(fmStart, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fmEnd, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbBreaktimetotask1)
                                        .addComponent(cbStatus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBreak, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbProject)
                                        .addComponent(cbProject, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbTaskName)
                                        .addComponent(cbTask, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtRemark, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19))
                                        .addGroup(GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                                .addComponent(jToggleButton1)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbWorktime)
                                        .addComponent(lbBreaktime)
                                        .addComponent(lbOvertime)
                                        .addComponent(fmTotal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fmOverTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fmBreakTime, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAddRecord)
                                        .addComponent(btnUpdateRecord)
                                        .addComponent(btnDelete))
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this); // THAY ĐỔI: Dùng 'this' thay vì getContentPane()
        this.setLayout(layout); // THAY ĐỔI: Dùng 'this' thay vì getContentPane()
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnlAddAttendance, GroupLayout.PREFERRED_SIZE, 841, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(pnlAddAttendance, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        // LOẠI BỎ: pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadUserInfo() {
        try {
            if (loggedInUser != null) {
                // Tên nhân viên
                txtEmployeeName.setText(loggedInUser.getUserName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadProjects() {
        try {
            ProjectDAO projectDAO = new ProjectDAO();
            List<Project> projects = projectDAO.findAll();

            cbProject.removeAllItems();
            for (Project p : projects) {
                cbProject.addItem(p.getName());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadTasks() {
        try {
            TaskDAO taskDAO = new TaskDAO();
            List<Tasks> tasks = taskDAO.findAll();

            cbTask.removeAllItems();
            for (Tasks t : tasks) {
                cbTask.addItem(t.getName());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private boolean validateForm() {

        // ==== 1. Ngày làm việc không được sau hôm nay ====
        Date today = new Date();
        Date selectedDate = csDate.getDate();

        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày làm việc!");
            return false;
        }

        if (selectedDate.after(today)) {
            JOptionPane.showMessageDialog(this, "Không được nhập ngày trong tương lai!");
            return false;
        }


        // ==== 2. Check-in bắt buộc ====
        String checkInStr = fmCheckIn.getText().trim();
        if (checkInStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giờ Check-in!");
            return false;
        }

        // Parse check-in
        LocalTime checkIn;
        try {
            checkIn = LocalTime.parse(checkInStr);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giờ Check-in không hợp lệ!");
            return false;
        }

        // ==== 3. Check-out: cho phép bỏ trống ====
        String checkOutStr = fmCheckOut.getText().trim();
        LocalTime checkOut = null;

        if (!checkOutStr.isEmpty()) {
            try {
                checkOut = LocalTime.parse(checkOutStr);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Giờ Check-out không hợp lệ!");
                return false;
            }

            // Nếu có nhập checkout → phải sau checkin
            if (checkOut.isBefore(checkIn)) {
                JOptionPane.showMessageDialog(this, "Check-out phải sau Check-in!");
                return false;
            }
        }
        // ==== 4. Validate Holiday ====
        if (rbHoliday.isSelected()) {

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String selectedStr = sdf.format(selectedDate);

            HolidayController holidayController = new HolidayController(new HolidayDAO());
            boolean isHoliday = holidayController.findAll()
                    .stream()
                    .anyMatch(h -> sdf.format(h.getDateHoliday()).equals(selectedStr));

            if (!isHoliday) {
                JOptionPane.showMessageDialog(this,
                        "Ngày này không phải ngày nghỉ! Không thể chọn Holiday.");
                rbHoliday.setSelected(false);
                return false;
            }
        }

        return true;
    }


    private void btnCreatecontentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatecontentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatecontentActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void btnWorkinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkinformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWorkinformationActionPerformed



    private void cbTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTaskActionPerformed

    private void btnAddAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAttendActionPerformed
        // TODO add your handling code here:
        if (!validateForm()) return;

        if (!validateForm()) return;

        Date selectedDate = csDate.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày!");
            return;
        }

        String checkInStr = fmCheckIn.getText().trim();
        String checkOutStr = fmCheckOut.getText().trim();

        if (checkInStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập giờ Check-in!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            LocalDate workDate = LocalDate.parse(sdf.format(selectedDate));
            LocalTime checkIn = LocalTime.parse(checkInStr);
            LocalTime checkOut = null;
            if (!checkOutStr.isEmpty()) {
                checkOut = LocalTime.parse(checkOutStr);
            }

            // 1. Tìm Attendance
            Attendance attendance = attendanceController.findByUserAndDate(loggedInUser.getId(), workDate)
                    .stream().findFirst().orElse(null);

            if (attendance == null) {
                // 2. Nếu chưa có -> tạo mới
                attendance = new Attendance();
                attendance.setUser(loggedInUser);
                attendance.setWorkDate(workDate);
                attendance.setCheckInTime(checkIn);
                attendance.setCheckOutTime(checkOut); // lưu luôn check-out nếu có
                attendance.setBreakMinutes(0);
                attendance.setHoliday(rbHoliday.isSelected());
                attendance.setStatus(Constant.ATTENDANCE_STATUS_PENDING);
                attendance.calculateTimes();
                attendance.setCreatedAt(LocalDateTime.now());
                attendance.setUpdatedAt(LocalDateTime.now());

                attendanceController.create(attendance);
            } else {
                // 3. Nếu đã có -> cập nhật
                if (attendance.getCheckInTime() == null) attendance.setCheckInTime(checkIn);
                if (checkOut != null) {
                    if (checkOut.isBefore(attendance.getCheckInTime())) {
                        JOptionPane.showMessageDialog(this, "Check-out không thể trước Check-in!");
                        return;
                    }
                    attendance.setCheckOutTime(checkOut);
                }

                // 4. Cập nhật breakMinutes từ WorkRecord
                int totalBreak = attendance.getWorkRecords().stream()
                        .mapToInt(w -> w.getBreakWork() == null ? 0 : w.getBreakWork())
                        .sum();
                attendance.setBreakMinutes(totalBreak);

                attendance.calculateTimes();
                attendance.setUpdatedAt(LocalDateTime.now());

                attendanceController.update(attendance);
            }

            JOptionPane.showMessageDialog(this, "Attendance đã được cập nhật thành công!");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAddAttendActionPerformed



    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void fmStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmStartActionPerformed

    private void fmEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmEndActionPerformed

    private void fmTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmTotalActionPerformed


    private void fmOverTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmOverTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmOverTimeActionPerformed

    private void fmBreakTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmBreakTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmBreakTimeActionPerformed

    private void fmCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmCheckInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmCheckInActionPerformed

    private void fmCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fmCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fmCheckOutActionPerformed

    private void btnAddRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecordActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Lấy Attendance hiện tại
            Attendance attendance = attendanceController.findByUserAndDate(
                    loggedInUser.getId(),
                    LocalDate.parse(new SimpleDateFormat("yyyy-MM-dd")
                            .format(csDate.getDate()))
            ).stream().reduce((first, second) -> second).orElse(null);

            if (attendance == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy Attendance hiện tại!");
                return;
            }

            // 2. Lấy dữ liệu giờ bắt đầu / kết thúc
            String startStr = fmStart.getText().trim();
            String endStr = fmEnd.getText().trim();

            if (startStr.isEmpty() || endStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập giờ bắt đầu và kết thúc!");
                return;
            }

            LocalTime start = LocalTime.parse(startStr);
            LocalTime end = LocalTime.parse(endStr);

            if (end.isBefore(start)) {
                JOptionPane.showMessageDialog(this, "Giờ kết thúc phải sau giờ bắt đầu!");
                return;
            }

            // 3. Lấy Project và Task
            String projectName = (String) cbProject.getSelectedItem();
            String taskName = (String) cbTask.getSelectedItem();

            Project project = new ProjectDAO().findByName(projectName).orElse(null);
            Tasks task = new TaskDAO().findByName(taskName).orElse(null);

            // 4. Tính tổng phút block
            long totalMinutes = Duration.between(start, end).toMinutes();

            //  breakWork của block này (mặc định 0 nếu không nhập break riêng)
            int breakWork = 0;
            try {
                String breakStr = txtBreak.getText().trim();
                if (!breakStr.isEmpty()) {
                    breakWork = Integer.parseInt(breakStr);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Số phút nghỉ phải là số nguyên!");
                return;
            }

            // workMinutes = tổng phút - nghỉ
            int workMinutes = (int) totalMinutes - breakWork;
            if (workMinutes < 0) {
                JOptionPane.showMessageDialog(this, "Phút nghỉ không thể lớn hơn tổng thời gian block!");
                return;
            }


            // 5. Lấy status WorkRecord
            int status;
            switch (cbStatus.getSelectedIndex()) {
                case 0 -> status = Constant.WORK_RECORD_STATUS_PENDING;   // 未確認
                case 1 -> status = Constant.WORK_RECORD_STATUS_APPROVED;  // 確認済み
                default -> status = Constant.WORK_RECORD_STATUS_REJECTED; // 拒否済み
            }

            // 6. Tạo mới WorkRecord
            WorkRecord detail = new WorkRecord();
            detail.setAttendance(attendance);
            detail.setProject(project);
            detail.setTask(task);
            detail.setStartTime(start);
            detail.setEndTime(end);
            detail.setBreakWork(breakWork);
            detail.setWorkMinutes(workMinutes);
            detail.setRemarks(txtRemark.getText().trim());
            detail.setStatus(status);
            detail.setCreatedAt(LocalDateTime.now());
            detail.setUpdatedAt(LocalDateTime.now());

            // 7. Lưu WorkRecord
            recordController.createRecord(detail);

            // 8. Cập nhật lại tổng breakMinutes của attendance
            int totalBreak =
                    attendance.getWorkRecords()
                            .stream()
                            .mapToInt(w -> w.getBreakWork() == null ? 0 : w.getBreakWork())
                            .sum();

            attendance.setBreakMinutes(totalBreak);

            attendanceController.update(attendance);

            // 9. Refresh table
            JOptionPane.showMessageDialog(this, "Thêm Work Record thành công!");
            loadWorkRecordTable(attendance.getId());

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAddRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // THAY ĐỔI: Main method tạo JFrame để chứa JPanel mới
        java.awt.EventQueue.invokeLater(() -> {
            // Cần tạo một đối tượng Users giả để test vì constructor yêu cầu
            Users dummyUser = new Users();
            dummyUser.setId(1); // Giả lập User ID
            dummyUser.setUserName("Test User");

            JFrame frame = new JFrame("AddAttendance Panel Wrapper");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new AddAttendance(dummyUser)); // Thêm JPanel vào JFrame
            frame.setSize(860, 680); // Cài đặt kích thước phù hợp
            frame.setVisible(true);
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnAddAttend;
    private JButton btnAddRecord;
    private JButton btnCreatecontent;
    private JButton btnDelete;
    private JButton btnUpdateRecord;
    private JButton btnWorkinformation;
    private ButtonGroup buttonGroup1;
    private ButtonGroup buttonGroup2;
    private JComboBox<String> cbProject;
    private JComboBox<String> cbStatus;
    private JComboBox<String> cbTask;
    private com.toedter.calendar.JDateChooser csDate;
    private JFormattedTextField fmBreakTime;
    private JFormattedTextField fmCheckIn;
    private JFormattedTextField fmCheckOut;
    private JFormattedTextField fmEnd;
    private JFormattedTextField fmOverTime;
    private JFormattedTextField fmStart;
    private JFormattedTextField fmTotal;
    private JComboBox<String> jComboBox3;
    private JLabel jLabel1;
    private JLabel jLabel12;
    private JLayeredPane jLayeredPane1;
    private JRadioButton jRadioButton1;
    private JScrollPane jScrollPane1;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JToggleButton jToggleButton1;
    private JLabel lbBreaktime;
    private JLabel lbBreaktimetotask;
    private JLabel lbBreaktimetotask1;
    private JLabel lbCalendar;
    private JLabel lbEarlieststarttime;
    private JLabel lbEmployee;
    private JLabel lbEndtime;
    private JLabel lbLatestendtime;
    private JLabel lbOvertime;
    private JLabel lbProject;
    private JLabel lbStarttime;
    private JLabel lbTaskName;
    private JLabel lbWorktime;
    private JPanel pnlAddAttendance;
    private java.awt.PopupMenu popupMenu1;
    private JRadioButton rbHoliday;
    private JTable tblRecord;
    private JTextField txtBreak;
    private JTextField txtEmployeeName;
    private JTextField txtRemark;
    private JLabel txtValidate;
    // End of variables declaration//GEN-END:variables
}