/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ra.View.attendance;

/**
 *
 * @author admin
 */
public class AddAttendance extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddAttendance.class.getName());

    /**
     * Creates new form AddAttendance
     */
    public AddAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        pnlAddAttendance = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAddAttendance = new javax.swing.JTable();
        btnWorkinformation = new javax.swing.JButton();
        btnCreatecontent = new javax.swing.JButton();
        lbEmployee = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        lbCalendar = new javax.swing.JLabel();
        txtCalendar = new javax.swing.JTextField();
        lbEarlieststarttime = new javax.swing.JLabel();
        lbHoliday = new javax.swing.JLabel();
        cbHoliday = new javax.swing.JComboBox<>();
        lbLatestendtime = new javax.swing.JLabel();
        txtEarlieststarttime = new javax.swing.JTextField();
        txtLatestendtime = new javax.swing.JTextField();
        txtValidate = new javax.swing.JLabel();
        lbStarttime = new javax.swing.JLabel();
        lbEndtime = new javax.swing.JLabel();
        txtBreaktimetotask = new javax.swing.JTextField();
        txtStarttime = new javax.swing.JTextField();
        txtEndtime = new javax.swing.JTextField();
        txtWorktimetotask = new javax.swing.JTextField();
        lbBreaktimetotask = new javax.swing.JLabel();
        lbWorktimetotask = new javax.swing.JLabel();
        lbProject = new javax.swing.JLabel();
        cbProject = new javax.swing.JComboBox<>();
        txtTask = new javax.swing.JComboBox<>();
        lbTaskName = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        lbWorktime = new javax.swing.JLabel();
        txtWorktime = new javax.swing.JTextField();
        txtOvertime = new javax.swing.JTextField();
        lbOvertime = new javax.swing.JLabel();
        txtBreaktime = new javax.swing.JTextField();
        lbBreaktime = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAddAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "＋", "順番", "プロジェクト名", "タスク名", "開始", "終了", "休憩時間", "勤務時間"
            }
        ));
        tblAddAttendance.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblAddAttendance);
        tblAddAttendance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        btnWorkinformation.setBackground(new java.awt.Color(255, 255, 204));
        btnWorkinformation.setText("勤怠情報");
        btnWorkinformation.addActionListener(this::btnWorkinformationActionPerformed);

        btnCreatecontent.setBackground(new java.awt.Color(255, 255, 204));
        btnCreatecontent.setText("作成内容");
        btnCreatecontent.addActionListener(this::btnCreatecontentActionPerformed);

        lbEmployee.setText("社員名");

        txtEmployeeName.setText("ログイン社員名");
        txtEmployeeName.addActionListener(this::txtEmployeeNameActionPerformed);

        lbCalendar.setText("日付");

        txtCalendar.setText("日 / 月 / 年");
        txtCalendar.addActionListener(this::txtCalendarActionPerformed);

        lbEarlieststarttime.setText("最始");

        lbHoliday.setText("休日");

        cbHoliday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbLatestendtime.setText("最終");

        txtEarlieststarttime.setText("時/分");
        txtEarlieststarttime.addActionListener(this::txtEarlieststarttimeActionPerformed);

        txtLatestendtime.setText("時/分");

        txtValidate.setFont(new java.awt.Font("Yu Gothic", 0, 8)); // NOI18N
        txtValidate.setForeground(new java.awt.Color(255, 0, 51));
        txtValidate.setText("※未来の値入力不可");

        lbStarttime.setText("開始");

        lbEndtime.setText("終了");

        txtBreaktimetotask.setText("時/分");
        txtBreaktimetotask.addActionListener(this::txtBreaktimetotaskActionPerformed);

        txtStarttime.setText("時/分");
        txtStarttime.addActionListener(this::txtStarttimeActionPerformed);

        txtEndtime.setText("時/分");
        txtEndtime.addActionListener(this::txtEndtimeActionPerformed);

        txtWorktimetotask.setText("時/分");
        txtWorktimetotask.addActionListener(this::txtWorktimetotaskActionPerformed);

        lbBreaktimetotask.setText("休憩");

        lbWorktimetotask.setText("勤務時間");

        lbProject.setText("プロジェクト名");

        cbProject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTask.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtTask.addActionListener(this::txtTaskActionPerformed);

        lbTaskName.setText("タスク名");

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setText("追加");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 204));
        jToggleButton1.setText("合計");
        jToggleButton1.addActionListener(this::jToggleButton1ActionPerformed);

        lbWorktime.setText("勤務時間");

        txtWorktime.setText("時/分");
        txtWorktime.addActionListener(this::txtWorktimeActionPerformed);

        txtOvertime.setText("時/分");

        lbOvertime.setText("残業時間");

        txtBreaktime.setText("時/分");

        lbBreaktime.setText("休憩時間");

        btnCancel.setBackground(new java.awt.Color(255, 204, 204));
        btnCancel.setText("キャンセル");

        btnSend.setBackground(new java.awt.Color(153, 204, 255));
        btnSend.setText("送信");

        javax.swing.GroupLayout pnlAddAttendanceLayout = new javax.swing.GroupLayout(pnlAddAttendance);
        pnlAddAttendance.setLayout(pnlAddAttendanceLayout);
        pnlAddAttendanceLayout.setHorizontalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnWorkinformation, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtValidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtCalendar)
                                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbEarlieststarttime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addComponent(txtEarlieststarttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25)
                                                .addComponent(lbLatestendtime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtLatestendtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                        .addGap(407, 407, 407)
                                        .addComponent(btnCancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSend))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddAttendanceLayout.createSequentialGroup()
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                        .addComponent(lbStarttime, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtStarttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbEndtime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtEndtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(47, 47, 47)
                                                        .addComponent(lbBreaktimetotask, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtBreaktimetotask, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addComponent(lbProject)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbProject, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(lbTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(lbWorktimetotask)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtWorktimetotask, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddAttendanceLayout.createSequentialGroup()
                                        .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCreatecontent, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbWorktime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtWorktime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(lbOvertime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(lbBreaktime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBreaktime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlAddAttendanceLayout.setVerticalGroup(
            pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                .addComponent(btnWorkinformation)
                .addGap(7, 7, 7)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbEmployee))
                    .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEarlieststarttime)
                        .addComponent(lbLatestendtime)
                        .addComponent(txtEarlieststarttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLatestendtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbCalendar))
                    .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbHoliday)
                        .addComponent(cbHoliday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(txtValidate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreatecontent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStarttime)
                    .addComponent(lbEndtime)
                    .addComponent(txtBreaktimetotask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStarttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWorktimetotask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEndtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBreaktimetotask)
                    .addComponent(lbWorktimetotask))
                .addGap(17, 17, 17)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProject)
                    .addComponent(cbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTaskName)
                    .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddAttendanceLayout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddAttendanceLayout.createSequentialGroup()
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWorktime)
                    .addComponent(txtWorktime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBreaktime)
                    .addComponent(txtBreaktime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbOvertime)
                    .addComponent(txtOvertime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAddAttendanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSend))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAddAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAddAttendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatecontentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatecontentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreatecontentActionPerformed

    private void txtCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalendarActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    private void txtEarlieststarttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEarlieststarttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEarlieststarttimeActionPerformed

    private void btnWorkinformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkinformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWorkinformationActionPerformed

    private void txtBreaktimetotaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBreaktimetotaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBreaktimetotaskActionPerformed

    private void txtStarttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStarttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStarttimeActionPerformed

    private void txtEndtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEndtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndtimeActionPerformed

    private void txtWorktimetotaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorktimetotaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorktimetotaskActionPerformed

    private void txtTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaskActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtWorktimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorktimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorktimeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddAttendance().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCreatecontent;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnWorkinformation;
    private javax.swing.JComboBox<String> cbHoliday;
    private javax.swing.JComboBox<String> cbProject;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbBreaktime;
    private javax.swing.JLabel lbBreaktimetotask;
    private javax.swing.JLabel lbCalendar;
    private javax.swing.JLabel lbEarlieststarttime;
    private javax.swing.JLabel lbEmployee;
    private javax.swing.JLabel lbEndtime;
    private javax.swing.JLabel lbHoliday;
    private javax.swing.JLabel lbLatestendtime;
    private javax.swing.JLabel lbOvertime;
    private javax.swing.JLabel lbProject;
    private javax.swing.JLabel lbStarttime;
    private javax.swing.JLabel lbTaskName;
    private javax.swing.JLabel lbWorktime;
    private javax.swing.JLabel lbWorktimetotask;
    private javax.swing.JPanel pnlAddAttendance;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JTable tblAddAttendance;
    private javax.swing.JTextField txtBreaktime;
    private javax.swing.JTextField txtBreaktimetotask;
    private javax.swing.JTextField txtCalendar;
    private javax.swing.JTextField txtEarlieststarttime;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEndtime;
    private javax.swing.JTextField txtLatestendtime;
    private javax.swing.JTextField txtOvertime;
    private javax.swing.JTextField txtStarttime;
    private javax.swing.JComboBox<String> txtTask;
    private javax.swing.JLabel txtValidate;
    private javax.swing.JTextField txtWorktime;
    private javax.swing.JTextField txtWorktimetotask;
    // End of variables declaration//GEN-END:variables
}
