/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ra.View.attendance;

import com.ra.Controller.AttendanceController;
import com.ra.Controller.UserController;
import com.ra.Model.Entity.Attendance;
import com.ra.Model.Entity.Users;
import com.ra.View.dashboard.MainDashboard;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author thuyhoang
 */
public class AttendanceDate extends javax.swing.JPanel {

    /**
     * Creates new form AttendanceDate
     */
    private AttendanceController attendanceController;
    private Users loggedInUser;
    private UserController userController;
    private OnViewListener viewListener;  // Callback khi view attendance

    // Interface để MainFrame lắng nghe (nếu cần)
    public interface OnViewListener {
        void onViewAttendance(List<Attendance> attendanceList);
    }

    public void setOnViewListener(OnViewListener listener) {
        this.viewListener = listener;
    }

    private boolean isManager(Users user) {
        if (user == null || user.getRole() == null) return false;
        int roleId = user.getRole().getId();   // 1=EMP, 2=MANAGER, 3=ADMIN
        return roleId == 2 || roleId == 3;
    }

    public AttendanceDate(Users user) {
        initComponents();
        this.loggedInUser = user;
        this.userController = new UserController();
        this.attendanceController = new AttendanceController();

        centerTableColumns(tblDate);
        initStatusComboBox();

        // Employee không được đổi trạng thái
        if (!isManager(loggedInUser)) {
            cbStatus.setVisible(false);
            btnStatus.setVisible(false);
            // 👇 ẨN TÌM KIẾM THEO TÊN NHÂN VIÊN
            txtAttendanceDate.setVisible(false);
            btnSearchField.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearchDate = new javax.swing.JButton();
        txtAttendanceDate = new javax.swing.JTextField();
        btnSearchField = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDate = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cbStatus = new javax.swing.JComboBox<>();
        btnStatus = new javax.swing.JButton();

        btnSearchDate.setText("検索");
        btnSearchDate.addActionListener(this::btnSearchDateActionPerformed);

        btnSearchField.setText("検索");
        btnSearchField.addActionListener(this::btnSearchFieldActionPerformed);

        tblDate.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null}
                },
                new String [] {
                        "No", "社員名", "開始時間", "終了時間", "休憩時間", "残業時間", "状態"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDate);

        btnView.setBackground(new java.awt.Color(204, 204, 255));
        btnView.setText("詳細");
        btnView.addActionListener(this::btnViewActionPerformed);

        btnStatus.setText("状態変更");
        btnStatus.addActionListener(this::btnStatusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnView)
                                .addGap(134, 134, 134))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(btnSearchDate)
                                                                .addGap(193, 193, 193)
                                                                .addComponent(txtAttendanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btnStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                        .addComponent(btnSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnSearchDate)
                                                .addComponent(txtAttendanceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSearchField)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnStatus)
                                        .addComponent(cbStatus))
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnView)
                                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tblDate.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "レコードを選択してください。");
            return;
        }

        try {
            String idStr = tblDate.getValueAt(row, 0).toString();
            int attendanceId = Integer.parseInt(idStr);

            Attendance attendance = attendanceController.findById(attendanceId);

            if (attendance == null) {
                JOptionPane.showMessageDialog(this, "データが存在しません。");
                return;
            }

            List<Attendance> list = new ArrayList<>();
            list.add(attendance);

            boolean editable = false;

            // trạng thái attendance
            int status = attendance.getStatus();

            // Manager → luôn edit được
            if (isManager(loggedInUser)) {
                editable = true;
            }
            // Employee → chỉ edit khi pending hoặc rejected
            else if (status == 0 || status == 2) {
                editable = true;
            }

            MainDashboard mainDashboard = findParentMainDashboard(this);

            if (mainDashboard != null) {

                // truyền viewMode = !editable
                AddAttendance addAttendancePanel =
                        new AddAttendance(mainDashboard.currentUser, list, !editable);

                mainDashboard.showPanel(addAttendancePanel);

                JOptionPane.showMessageDialog(this,
                        editable
                                ? "編集可能モードで開きました。"
                                : "閲覧モード：修正できません。",
                        "情報",
                        JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "エラー: " + e.getMessage());
        }
    }
//GEN-LAST:event_btnViewActionPerformed

    // Helper: tìm MainDashboard parent
    private MainDashboard findParentMainDashboard(Component component) {
        Container parent = component.getParent();
        while (parent != null) {
            if (parent instanceof MainDashboard) {
                return (MainDashboard) parent;
            }
            parent = parent.getParent();
        }
        return null;
    }

    private String formatMinutesToHours(int minutes) {
        int h = minutes / 60;
        int m = minutes % 60;
        return String.format("%d時間%d分", h, m);
    }

    private String formatTimeWithExtraDay(LocalTime time, int extraDay) {
        if (time == null) return "";
        int hour = time.getHour() + extraDay * 24;
        return String.format("%02d:%02d", hour, time.getMinute());
    }

    private String getStatusJapanese(int status) {
        return switch (status) {
            case 0 -> "未確認";   // Pending
            case 1 -> "確認済み"; // Approved
            case 2 -> "拒否済み"; // Rejected
            default -> "不明";
        };
    }

    private void centerTableColumns(JTable table) {
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(center);
        }
    }

    private void btnSearchDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDateActionPerformed
        try {
            java.util.Date selectedDate = jDateChooser1.getDate();

            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this, "日付を選択してください。");
                return;
            }

            LocalDate localDate =
                    new java.sql.Date(selectedDate.getTime()).toLocalDate();

            List<Attendance> list =
                    attendanceController.findByDate(localDate);

            if (list == null || list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "該当するデータがありません。");
                return;
            }

            String[] cols = {
                    "ID", "No", "日付", "社員名", "開始時間", "終了時間",
                    "勤務時間", "休憩時間", "残業時間", "状態"
            };

            DefaultTableModel model = new DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int r, int c) { return false; }
            };

            for (int i = 0; i < list.size(); i++) {
                Attendance a = list.get(i);

                model.addRow(new Object[]{
                        a.getId(),
                        i + 1,
                        a.getWorkDate(),
                        a.getUser().getUserName(),
                        a.getCheckInTime(),
                        // nếu có extraDay thì hiển thị chuẩn
                        formatTimeWithExtraDay(a.getCheckOutTime(), a.getExtraDay()),
                        formatMinutesToHours(a.getTotalMinutes()),
                        a.getBreakMinutes() + "分",
                        a.getOvertimeMinutes() + "分",
                        getStatusJapanese(a.getStatus())
                });
            }

            tblDate.setModel(model);
            // Ẩn cột ID
            tblDate.getColumnModel().getColumn(0).setMinWidth(0);
            tblDate.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDate.getColumnModel().getColumn(0).setWidth(0);

            centerTableColumns(tblDate);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "検索エラー: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchDateActionPerformed

    private void initStatusComboBox() {
        cbStatus.removeAllItems();
        cbStatus.addItem("未確認");   // Status 0
        cbStatus.addItem("確認済み"); // Status 1
        cbStatus.addItem("拒否済み"); // Status 2
    }

    private void btnStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusActionPerformed
        try {
            // 🔐 Chỉ MANAGER / ADMIN được đổi trạng thái
            if (!isManager(loggedInUser)) {
                JOptionPane.showMessageDialog(this,
                        "この操作を行う権限がありません。\n" +
                                "ステータス変更はマネージャー／管理者のみ可能です。");
                return;
            }

            // 1. Lấy trạng thái được chọn từ combobox
            String selectedStatus = cbStatus.getSelectedItem().toString();

            int dbStatus = switch (selectedStatus) {
                case "未確認" -> 0;
                case "確認済み" -> 1;
                case "拒否済み" -> 2;
                default -> -1;
            };

            if (dbStatus == -1) {
                JOptionPane.showMessageDialog(this, "無効な状態です。");
                return;
            }

            // 2. Kiểm tra xem có dòng nào được chọn trong bảng không
            int selectedRow = tblDate.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "更新する行を選択してください。");
                return;
            }

            // 3. Lấy ID của bản ghi attendance từ dòng được chọn (cột 0 đang ẩn)
            DefaultTableModel model = (DefaultTableModel) tblDate.getModel();
            int attendanceId = (int) model.getValueAt(selectedRow, 0);

            // 4. Tìm và cập nhật attendance
            Attendance attendance = attendanceController.findById(attendanceId);
            if (attendance == null) {
                JOptionPane.showMessageDialog(this, "勤怠データが見つかりません。");
                return;
            }

            // 5. Cập nhật trạng thái
            attendance.setStatus(dbStatus);
            Attendance updatedAttendance = attendanceController.updateStatus(attendance);

            if (updatedAttendance != null) {
                // 6. Cập nhật lại bảng theo status vừa chọn
                // 6. Chỉ cập nhật lại dòng đang chọn, không refresh toàn bảng
                int statusColumnIndex = 9; // cột "状態" = cột thứ 9
                model.setValueAt(getStatusJapanese(dbStatus), selectedRow, statusColumnIndex);

                JOptionPane.showMessageDialog(this, "ステータスが更新されました。");
            } else {
                JOptionPane.showMessageDialog(this, "更新に失敗しました。");
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "エラー: " + e.getMessage());
        }
    }//GEN-LAST:event_btnStatusActionPerformed

    // Cập nhật bảng theo user + status
    private void refreshAttendanceTableByStatus(int userId, int status) {
        try {
            List<Attendance> list =
                    attendanceController.findByUserAndStatus(userId, status);

            String[] columns = {
                    "ID", "日付", "社員名", "開始時間", "終了時間",
                    "勤務時間", "休憩時間", "残業時間", "状態"
            };

            DefaultTableModel model = new DefaultTableModel(columns, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            if (list != null) {
                for (Attendance a : list) {
                    model.addRow(new Object[]{
                            a.getId(),
                            a.getWorkDate(),
                            a.getUser().getUserName(),
                            a.getCheckInTime(),
                            formatTimeWithExtraDay(a.getCheckOutTime(), a.getExtraDay()),
                            formatMinutesToHours(a.getTotalMinutes()),
                            a.getBreakMinutes() + "分",
                            a.getOvertimeMinutes() + "分",
                            getStatusJapanese(a.getStatus())
                    });
                }
            }

            tblDate.setModel(model);
            // Ẩn cột ID
            tblDate.getColumnModel().getColumn(0).setMinWidth(0);
            tblDate.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDate.getColumnModel().getColumn(0).setWidth(0);

            centerTableColumns(tblDate);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void btnSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchFieldActionPerformed
        String username = txtAttendanceDate.getText().trim();

        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "社員名を入力してください。");
            return;
        }

        try {
            List<Attendance> list = attendanceController.findByUsername(username);

            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "該当するデータがありません。");
                return;
            }

            String[] cols = {
                    "ID", "No", "日付", "社員名", "開始時間", "終了時間",
                    "勤務時間", "休憩時間", "残業時間", "状態"
            };

            DefaultTableModel model = new DefaultTableModel(cols, 0) {
                @Override
                public boolean isCellEditable(int r, int c) { return false; }
            };

            for (int i = 0; i < list.size(); i++) {
                Attendance a = list.get(i);

                model.addRow(new Object[]{
                        a.getId(),
                        i + 1,
                        a.getWorkDate(),
                        a.getUser().getUserName(),
                        a.getCheckInTime(),
                        formatTimeWithExtraDay(a.getCheckOutTime(), a.getExtraDay()),
                        formatMinutesToHours(a.getTotalMinutes()),
                        a.getBreakMinutes() + "分",
                        a.getOvertimeMinutes() + "分",
                        getStatusJapanese(a.getStatus())
                });
            }

            tblDate.setModel(model);
            // Ẩn cột ID
            tblDate.getColumnModel().getColumn(0).setMinWidth(0);
            tblDate.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDate.getColumnModel().getColumn(0).setWidth(0);

            centerTableColumns(tblDate);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "検索エラー: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchDate;
    private javax.swing.JButton btnSearchField;
    private javax.swing.JButton btnStatus;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cbStatus;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDate;
    private javax.swing.JTextField txtAttendanceDate;
    // End of variables declaration//GEN-END:variables
}
