/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ra.View.user;

import com.ra.View.button.ButtonRenderer;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
/**
 *
 * @author Admin
 */
public class AllUser extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AllUser.class.getName());

    /**
     * Creates new form AllUser
     */
    public AllUser() {
        initComponents();
        // **********************************************
        // GỌI PHƯƠNG THỨC THIẾT LẬP CỘT NÚT
        // **********************************************
        setupButtonColumns(tbAlluser);
        // tblAllmenu là tên biến JTable của bạn, đã được khởi tạo ở initComponents()
    }


    // *************************************************************
    // THÊM PHƯƠNG THỨC THIẾT LẬP CỘT NÚT (CODE CẦU NỐI)
    // *************************************************************
    private void setupButtonColumns(JTable table) {

        // === Cột 4: Chỉnh sửa (編集) ===
        // Index cột 3 (vì cột bắt đầu từ 0: 0, 1, 2, 3, 4)
        TableColumn editColumn = table.getColumnModel().getColumn(6);

        // Khởi tạo ButtonEditor và ButtonRenderer cho cột "編集"
        // LƯU Ý: Đảm bảo ButtonRenderer.java và ButtonEditor.java
        // đã được đặt trong package com.ra.View.menu;

        // Renderer (Hiển thị nút)
        editColumn.setCellRenderer(new ButtonRenderer("編集"));



        // === Cột 5: Xóa (削除) ===
        TableColumn deleteColumn = table.getColumnModel().getColumn(7); // Index cột 4

        // Renderer (Hiển thị nút)
        deleteColumn.setCellRenderer(new ButtonRenderer("削除"));


        // Tùy chỉnh chiều rộng cột (Tùy chọn)
        editColumn.setPreferredWidth(60);
        deleteColumn.setPreferredWidth(60);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        pnlAllUser = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnAlluser = new javax.swing.JButton();
        btnAdduser = new javax.swing.JButton();
        scrollTable = new javax.swing.JScrollPane();
        tbAlluser = new javax.swing.JTable();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ユーザーリスト");
        setPreferredSize(new java.awt.Dimension(600, 400));

        pnlAllUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlAllUser.setPreferredSize(new java.awt.Dimension(600, 400));

        txtSearch.setText("jTextField1");
        txtSearch.setToolTipText("");
        txtSearch.addActionListener(this::txtSearchActionPerformed);

        btnSearch.setText("検索");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        btnAlluser.setText("すべて");
        btnAlluser.addActionListener(this::btnAlluserActionPerformed);

        btnAdduser.setBackground(new java.awt.Color(201, 221, 201));
        btnAdduser.setText("新ユーザー作成");

        tbAlluser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ユーザーコード", "社員名", "ユーザー名", "部署", "タスク", "ロール", "編集", "削除"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTable.setViewportView(tbAlluser);

        javax.swing.GroupLayout pnlAllUserLayout = new javax.swing.GroupLayout(pnlAllUser);
        pnlAllUser.setLayout(pnlAllUserLayout);
        pnlAllUserLayout.setHorizontalGroup(
            pnlAllUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllUserLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlluser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdduser, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(pnlAllUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlAllUserLayout.setVerticalGroup(
            pnlAllUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllUserLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlAllUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnAlluser)
                    .addComponent(btnAdduser))
                .addGap(18, 18, 18)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAllUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAllUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("User List");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAlluserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlluserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlluserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AllUser().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdduser;
    private javax.swing.JButton btnAlluser;
    private javax.swing.JButton btnSearch;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JPanel pnlAllUser;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable tbAlluser;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
