package com.ra.View.user;

import com.ra.Controller.UserController;
import com.ra.DAO.Auth.AuthDAO;
import com.ra.DAO.Department.DepartmentDAO;
import com.ra.DAO.Task.TaskDAO;
import com.ra.Model.Entity.Department;
import com.ra.Model.Entity.Roles;
import com.ra.Model.Entity.Tasks;
import com.ra.Model.Entity.Users;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 *
 * @author Admin
 */
public class EditUser extends JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditUser.class.getName());

    /**
     * Creates new form AddUser
     */
    private DefaultListModel<String> taskModel = new DefaultListModel<>();

    private UserController userController = new UserController();
    private Users currentUser;

    // BIẾN THAM CHIẾU ĐẾN ALLUSER ĐỂ GỌI REFRESH BẢNG
    private AllUser parentPanel;

    // SỬA CONSTRUCTOR ĐỂ NHẬN THÊM THAM CHIẾU ALLUSER
    public EditUser(Users users, AllUser parentPanel) {
        initComponents();
        listTask.setModel(taskModel);
        listTask.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // --- Thêm đoạn MouseListener để click thường chọn được nhiều ---
        listTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int index = listTask.locationToIndex(evt.getPoint());
                if (index >= 0) {
                    if (listTask.isSelectedIndex(index)) {
                        listTask.removeSelectionInterval(index, index);
                    } else {
                        listTask.addSelectionInterval(index, index);
                    }
                }
            }
        });

        // Gán tham chiếu và dữ liệu User
        this.parentPanel = parentPanel; // GÁN THAM CHIẾU
        this.currentUser = users;

        loadData();
        loadUserData();


    }

    // GIỮ CONSTRUCTOR CŨ NẾU CẦN CHẠY MAIN TRONG EDITUSER MÀ KHÔNG GÂY LỖI
    public EditUser(Users users) {
        this(users, null);
    }

    private void loadData() {
        loadDepartments();
        loadTasks();
        loadRoles();

    }
    private void loadUserData() {
        if (currentUser == null) return;

        txtMail.setText(currentUser.getEmail());
        txtUsername.setText(currentUser.getUserName());
        txtPassword.setText(currentUser.getPassword());
        txtEmployeename.setText(currentUser.getFullName());

        if (currentUser.getDepartment() != null) {
            cbDepartment.setSelectedItem(currentUser.getDepartment().getName());
        }

        if (currentUser.getRole() != null) {
            cbRole.setSelectedItem(currentUser.getRole().getName());
        }

        List<Tasks> userTasks = currentUser.getTasks();
        if (userTasks == null) return;

        DefaultListModel<String> model = (DefaultListModel<String>) listTask.getModel();

        // Duyệt từng task của user
        for (Tasks task : userTasks) {
            String taskName = task.getName();

            // Tìm index trong JList
            for (int i = 0; i < model.size(); i++) {
                if (model.get(i).equals(taskName)) {
                    listTask.addSelectionInterval(i, i);
                }
            }
        }

    }
    private void loadDepartments() {
        try {
            DepartmentDAO departmentDAO = new DepartmentDAO();
            List<Department> departments = departmentDAO.findAll();

            cbDepartment.removeAllItems();
            for (Department d : departments) {
                cbDepartment.addItem(d.getName());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadTasks() {
        try {
            TaskDAO taskDAO = new TaskDAO();
            List<Tasks> tasks = taskDAO.findAll();

            taskModel.clear();

            for (Tasks t : tasks) {
                taskModel.addElement(t.getName());
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    private void loadRoles() {
        try{
            AuthDAO authDAO = new AuthDAO();
            List<Roles> roles = authDAO.findAllRoles();
            cbRole.removeAllItems();
            for (Roles r : roles) {
                cbRole.addItem(r.getName());
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jFrame1 = new JFrame();
        jCheckBoxMenuItem4 = new JCheckBoxMenuItem();
        jCheckBoxMenuItem5 = new JCheckBoxMenuItem();
        jMenuItem1 = new JMenuItem();
        pnlAdduser = new JPanel();
        lbMail = new JLabel();
        txtMail = new JTextField();
        lbUsername = new JLabel();
        txtUsername = new JTextField();
        lbPassword = new JLabel();
        txtPassword = new JTextField();
        lbEmployeename = new JLabel();
        txtEmployeename = new JTextField();
        lbDepartment = new JLabel();
        lbTask = new JLabel();
        lbRole = new JLabel();
        cbRole = new JComboBox<>();
        btnSave = new JButton();
        cbDepartment = new JComboBox<>();
        jOptionPane1 = new JOptionPane();
        jSeparator1 = new JSeparator();
        jScrollPane1 = new JScrollPane();
        listTask = new JList<>();


        GroupLayout jFrame1Layout = new GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
                jFrame1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE)
        );

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("jCheckBoxMenuItem4");

        jCheckBoxMenuItem5.setSelected(true);
        jCheckBoxMenuItem5.setText("jCheckBoxMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); // ĐÃ SỬA: Dùng DISPOSE_ON_CLOSE
        setTitle("ユーザー更新");
        setPreferredSize(new java.awt.Dimension(600, 400));

        pnlAdduser.setBackground(new java.awt.Color(255, 255, 255));
        pnlAdduser.setPreferredSize(new java.awt.Dimension(600, 400));

        lbMail.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbMail.setText("メール");

        txtMail.addActionListener(this::txtMailActionPerformed);

        lbUsername.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbUsername.setText("ユーザー名");

        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        lbPassword.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbPassword.setText("パスワード");

        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        lbEmployeename.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbEmployeename.setText("社員名");

        txtEmployeename.addActionListener(this::txtEmployeenameActionPerformed);

        lbDepartment.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbDepartment.setText("部署");

        lbTask.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbTask.setText("タスク");

        lbRole.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        lbRole.setText("ロール");

        cbRole.setModel(new DefaultComboBoxModel<>(new String[] { "Employee", "Manager", "Admin" }));
        cbRole.addActionListener(this::cbRoleActionPerformed);


        btnSave.setBackground(new java.awt.Color(189, 231, 189));
        btnSave.setFont(new java.awt.Font("Yu Mincho", 1, 14)); // NOI18N
        btnSave.setText("保存");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        jScrollPane1.setViewportView(listTask);

        GroupLayout pnlAdduserLayout = new GroupLayout(pnlAdduser);
        pnlAdduser.setLayout(pnlAdduserLayout);
        pnlAdduserLayout.setHorizontalGroup(
                pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                                .addComponent(lbMail)
                                                                                .addGap(22, 22, 22))
                                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                                .addComponent(lbPassword)
                                                                                .addGap(19, 19, 19))
                                                                        .addGroup(GroupLayout.Alignment.LEADING, pnlAdduserLayout.createSequentialGroup()
                                                                                .addComponent(lbUsername)
                                                                                .addGap(19, 19, 19)))
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(txtPassword, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                                                        .addComponent(txtUsername, GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtMail, GroupLayout.Alignment.LEADING))
                                                                .addGap(52, 52, 52))
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addComponent(lbRole)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cbRole, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(53, 53, 53)))
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addComponent(lbTask)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
                                                                .addGap(123, 123, 123)
                                                                .addComponent(jOptionPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbEmployeename)
                                                                        .addComponent(lbDepartment))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(txtEmployeename, GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                                                        .addComponent(cbDepartment, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addGap(188, 188, 188)
                                                .addGap(36, 36, 36)
                                                .addComponent(btnSave)))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAdduserLayout.setVerticalGroup(
                pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMail)
                                        .addComponent(txtMail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbEmployeename)
                                        .addComponent(txtEmployeename, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtUsername, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbUsername)))
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(cbDepartment, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbDepartment))))
                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txtPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbPassword)
                                                        .addComponent(lbTask))
                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jOptionPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(cbRole, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(lbRole))
                                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(pnlAdduserLayout.createSequentialGroup()
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63)))
                                .addGroup(pnlAdduserLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave))
                                .addGap(74, 74, 74))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlAdduser, GroupLayout.PREFERRED_SIZE, 599, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlAdduser, GroupLayout.PREFERRED_SIZE, 401, GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Add User");

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMailActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtEmployeenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeenameActionPerformed

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed


    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            if (currentUser == null) {
                JOptionPane.showMessageDialog(this, "ユーザーが存在しません！");
                return;
            }

            // Lấy dữ liệu từ form
            String userName = txtUsername.getText();
            String password = txtPassword.getText();
            String roleName = cbRole.getSelectedItem().toString();
            String email = txtMail.getText();
            String fullName = txtEmployeename.getText();
            String departmentName = cbDepartment.getSelectedItem().toString();


            currentUser.setUserName(userName);
            currentUser.setPassword(password);
            currentUser.setEmail(email);
            currentUser.setFullName(fullName);

            // Department
            DepartmentDAO departmentDAO = new DepartmentDAO();
            Department dept = departmentDAO.findFindByName(departmentName).orElse(null);
            if (dept != null) {
                currentUser.setDepartment(dept);
            }

            // Role
            AuthDAO roleDAO = new AuthDAO();
            Optional<Roles> roleOpt = roleDAO.findByName(roleName);
            if (roleOpt.isPresent()) {
                currentUser.setRole(roleOpt.get());
            } else {
                JOptionPane.showMessageDialog(this, "Role không tồn tại!");
                return;
            }

            // Tasks
            TaskDAO taskDAO = new TaskDAO();
            // Lấy danh sách task đã chọn từ JList
            List<String> selectedTasks = listTask.getSelectedValuesList();

            // Luôn tạo list mới (tránh bị ghi đè vào list cũ đang dùng của Hibernate)
            List<Tasks> newTasks = new ArrayList<>();

            for (String name : selectedTasks) {
                taskDAO.findByName(name).ifPresent(newTasks::add);
            }

            // Gán danh sách task mới cho user
            currentUser.setTasks(newTasks);

            // Gọi Controller để update
            userController.updateUser(currentUser);

            JOptionPane.showMessageDialog(this, "ユーザーが正常に更新されました！");

            // GỌI PHƯƠNG THỨC REFRESH BẢNG TRONG ALLUSER
            if (parentPanel != null) {
                parentPanel.loadUserTable();
            }

            this.dispose(); // đóng form sau khi lưu
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
//GEN-LAST:event_btnSaveActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        // 🌟 CHỈ KHỞI TẠO, KHÔNG GỌI setVisible(true) 🌟
        java.awt.EventQueue.invokeLater(() -> new EditUser(new Users()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnSave;
    private JComboBox<String> cbDepartment;
    private JComboBox<String> cbRole;
    private JCheckBoxMenuItem jCheckBoxMenuItem4;
    private JCheckBoxMenuItem jCheckBoxMenuItem5;
    private JFrame jFrame1;
    private JMenuItem jMenuItem1;
    private JOptionPane jOptionPane1;
    private JScrollPane jScrollPane1;
    private JSeparator jSeparator1;
    private JLabel lbDepartment;
    private JLabel lbEmployeename;
    private JLabel lbMail;
    private JLabel lbPassword;
    private JLabel lbRole;
    private JLabel lbTask;
    private JLabel lbUsername;
    private JList<String> listTask;
    private JPanel pnlAdduser;
    private JTextField txtEmployeename;
    private JTextField txtMail;
    private JTextField txtPassword;
    private JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}